### ISSUE TITLE
Implement textDocument/selectionRange

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml-lsp#100]
The most recent version of the specification (3.15) introduced a `textDocument/selectionRange` request. This request is supposed to suggest available selections to the server.

This very closely corresponds to the `Shape` command in merlin (cf `query_protocol.ml`). There is just a bit of a mismatch because merlin returns a tree of shapes (every shape can have many sub shapes), so we'll need to do some intelligent flattening. This last bit we can tweak experimentally after trying out an initial implementation.

**Comment by cannorin** [comment]
I will work on this.
