### ISSUE TITLE
the main `lsp` entry point should catch exceptions

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocaml-lsp#101]
` Lsp.Rpc.start state handler ic oc; ` could have a catch all + logging, so that a stray `failwith` or `invalid_arg` doesn't kill the whole thing?
cc @Gbury

**Comment by giltho** [comment]
To be exact :
 - if the exception happens during the handling of a notification, it should just log what happens
 - if the exception happens during the handling of a request, it should answer with a `ResponseErro`r and code `InternalError` and the appropriate message. Also, possibly log the message.
