### ISSUE TITLE
Turn off semantic highlighting

### ISSUE THREAD

**Issue by paulpatault** [ocaml/ocaml-lsp#1030]
Is there a way to disable semantic highlighting ?

**Comment by tatchi** [comment]
Yes, you can add the following to your VSCode settings file:

```json
"[ocaml.interface]": {
    "editor.semanticHighlighting.enabled": false,
},
"[ocaml]": {
    "editor.semanticHighlighting.enabled": false,
},
```

**Comment by rgrinberg** [comment]
Disabling should be done through the client as tatchi directed. Let us know if it doesn't work.

**Comment by paulpatault** [comment]
I finally found a solution for my neovim setup.
The following functions do the job
```lua
vim.lsp.semantic_tokens.start
vim.lsp.semantic_tokens.stop
```
Thanks for your help!
