### ISSUE TITLE
jsonrpc: allow arbitrary error codes

### ISSUE THREAD

**Issue by sim642** [ocaml/ocaml-lsp#1044]
Not an issue with ocaml-lsp specifically but just the general jsonrpc library published from here.

Currently JSON-RPC error codes are just a fixed enum with standard codes from the JSON-RPC and LSP specifications:
https://github.com/ocaml/ocaml-lsp/blob/0c5651cd4adb83623962eab1eaadf28d521b7ca5/jsonrpc/src/jsonrpc.ml#L102-L116

This makes it impossible to emit or parse JSON-RPC packets with any other error codes, although the JSON-RPC specification allows applications to do so using custom values. It would be great if the jsonrpc library allowed the same.

Changing the error code type to `int` means breaking changes though. Standard error codes could be provided via extra value definitions to simplify emitting errors, but it won't be as convenient for pattern matching on parsing.

**Comment by rgrinberg** [comment]
You could an additional constructor for custom codes. Would you like to send a PR for that?

**Comment by sim642** [comment]
That's certainly a straightforward possibility and I'm willing to open a PR.

It leaves some asymmetry and bias though. For example `ParseError` and `Custom (-32700)` would both serialize to the same thing, but deserialize to `ParseError`. Having LSP-specific codes hard-coded could also be a bit odd for non-LSP uses which might prefer deserializing to `Custom (-32002)` rather than some application-unrelated `ServerNotInitialized.

Of course this is purely hypothetical and an extra constructor would already cover almost all use cases. Based on a quick look, it seems like the error codes aren't really used for pattern matching anyway (except maybe a couple of places), so going over to values would just mean lowercasing the current names at all error creation sites.

**Comment by rgrinberg** [comment]
> Having LSP-specific codes hard-coded could also be a bit odd for non-LSP uses which might prefer deserializing to Custom (-32002) rather than some application-unrelated `ServerNotInitialized.

It would be a bit inconvenient, but fixable with a simple pattern match.

This seems like a simple enough issue that I doubt many users would care what the approach is. I'm not against changing the code to an integer either. It just seems like that for such an edge case, we might as well do the minimum necessary and move on.
