### ISSUE TITLE
support refmt for Reason files

### ISSUE THREAD

**Issue by tsnobip** [ocaml/ocaml-lsp#106]
Reason support was added recently, it works quite well included, what's missing now is to support `refmt` instead of `ocamlformat` for Reason files.

If it's not too complicated, I can try my luck on it, any pointer will be appreciated :)

**Comment by rgrinberg** [comment]
This shouldn't be particularly difficult. Did you familiarize yourself with how the `ocamlformat` support works? https://github.com/ocaml/ocaml-lsp/blob/master/ocaml-lsp-server/src/ocaml_lsp_server.ml#L645-L653

Making this work for `refmt` should be quite similar. There needs to be a way to detect if we're in reason mode, and I guess the easiest way to do this is via the document URI. Perhaps there's a better approach than this however.

You can start this by introducing a `Refmt` module in the same spirit as `Ocamlformat` and we can proceed from there.

**Comment by tsnobip** [comment]
@rgrinberg I opened a PR to solve this issue, I'll update it accordingly to your remarks.

**Comment by tsnobip** [comment]
Closing this issue since #112 was merged
