### ISSUE TITLE
Ocaml lsp Unbound Module Base?

### ISSUE THREAD

**Issue by Jalanjii** [ocaml/ocaml-lsp#1060]
I have Ocaml switch 4.13.1 running on Mac. utop is working fine, can load the Base module when I do: 
```
#use "topfind";;
#require "base";;
open Base
List.mem ["1"] "1" ~equal:String.equal
```
even though I followed these instructions https://dev.realworldocaml.org/install.html which assume I don't have even to do `open Base`, but the VS Code is having a problem loading the Base module. I have OCaml -LSP language server installed for VS code for the switch I have. But when I try the above code, it gives me red error squiggly line under the `#` of `#use "topfind";;`. When I remove `use` and `require` I get the following error in the screenshot attached. Can you please help with this? I have tried everything since yesterday, I tried to build a project with dune and still in the main the above code have squiggly lines.

![231652998-a5b5dc96-d11b-4a23-bdab-3604e2663f88](https://user-images.githubusercontent.com/30749788/231834969-0d1495f9-09ff-4d17-8348-7693c91e6a83.jpg)

**Comment by copy** [comment]
merlin (and by extension, ocaml-lsp) doesn't support toplevel directives (`#require`, `#load`, etc.). You should write a dune file: https://ocaml.org/docs/compiling-ocaml-projects#dune-an-automated-build-system and use dune to build your code.
