### ISSUE TITLE
IO monad leaks assumption about binding behavior

### ISSUE THREAD

**Issue by ddickstein** [ocaml/ocaml-lsp#1075]
The lsp library abstracts over an Io monad with a `write` implementation, but it invokes `write` twice across a bind with an assumption that those writes will not be interleaved ([code](https://github.com/ocaml/ocaml-lsp/blob/master/lsp/src/io.ml#L115-L116)). This assumption may hold for the fiber implementation, but it does not necessarily hold for any monad. The writes need to be sequenced.

**Comment by rgrinberg** [comment]
Good point. In my implementation, I serialize the writes myself, but that does make the interface a bit fragile.

How about I change the write function to take  a `string list`?

**Comment by ddickstein** [comment]
That sounds fine to me
