### ISSUE TITLE
vendored lib imposes Dune ≥ 2.0

### ISSUE THREAD

**Issue by smondet** [ocaml/ocaml-lsp#108]
I don't know if this is expected but

```
#=== ERROR while compiling ocaml-lsp-server.~dev ==============================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(git+https://github.com/ocaml/ocaml-lsp.git#3e208720)
# path                 ~/zzz/dev/tezos/_opam/.opam-switch/build/ocaml-lsp-server.~dev
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -j 3 --root . --ignore-promoted-rules --no-config --profile release ocaml-lsp-server.install
# exit-code            1
# env-file             ~/.opam/log/ocaml-lsp-server-1538-de96f2.env
# output-file          ~/.opam/log/ocaml-lsp-server-1538-de96f2.out
### output ###
# File "vendor/ocaml-syntax-shims/dune-project", line 1, characters 11-14:
# 1 | (lang dune 2.0)
#                ^^^
# Error: Version 2.0 of dune is not supported.
# Supported versions:
# - 0.0
# - 1.0 to 1.11
```

Here:
https://github.com/ocaml/ocaml-lsp/blob/master/ocaml-lsp-server.opam#L45
the comment says:

>  `# so we do this manually to be compat with dune 1.0 and dune 2.0`

**Comment by rgrinberg** [comment]
We will try to lift this restriction in the future, but for now it's unlikely. Dune 2.x isn't that new anymore, so I'd like to hear some good reasons to stick to 1.x before committing to it. Do you have any projects that are tied to 1.x still?

**Comment by smondet** [comment]
Tezos (& hence a few satellite projects) is on 1.x still. it's a pretty big dependency cone that has to move somewhat slowishly (100s of users, many of them building from source, with custom opam-repository, while some dependencies still have `jbuild` files I think).

**Comment by smondet** [comment]
also, Dune 2.x is **very** new ;)
3 months, when you have 10s of projects to upgrade, work & personal, is extremely short
(esp since for existing projects in "maintenance-mode" dune 2.x doesn't bring almost anything useful)

![screenshot-20200228-003300](https://user-images.githubusercontent.com/617111/75513168-fa3bba80-59c1-11ea-88d2-557f969f2c1e.png)

**Comment by rgrinberg** [comment]
On the other hand, the upgrade to dune 2.0 is quite simple for all the projects that I’ve seen, and we are even preparing a tool to automate the process.

The way the I see it, ocamllsp is a new project that is developing rapidly. If we allow ourselves to get bogged down by all these dependency concerns, we aren’t going to make the progress that we want. However, once the project is mature and more widely adopted, we can start spending time on making it more widely available.

I’m pretty confident that most people will forget about dune 1.x in the next few months and dune 2.x will dominate. And if that isn’t the case, we can revisit this and bring back the 1.x support.

**Comment by rgrinberg** [comment]
I'm closing this. We're relying on a few dune 2.x features at this point and it would not be possible to revert back. Let's try to move other projects to dune 2.x instead.
