### ISSUE TITLE
Add support to disable settings through `didChangeConfiguration`

### ISSUE THREAD

**Issue by aspeddro** [ocaml/ocaml-lsp#1102]
Some settings can be disabled by the user. Currently the server has no means of disabling these features at the server level.

VSCode can disable codelens through the following setting:

```json
"[ocaml]": {
  "editor.codeLens": false
}
```

However other clients may not have means of disabling settings, such as Neovim.

### Suggested settings for the user to control

- Codelens
- Hover Extended

### Example config schema

```ocaml
"ocaml.codelens.enable": false,
"ocaml.hover.extended.enable": true
```

**Comment by rgrinberg** [comment]
Sure, that's a reasonable request. Feel free to send a PR.
