### ISSUE TITLE
Uri lib is incomplete

### ISSUE THREAD

**Issue by ajbt200128** [ocaml/ocaml-lsp#1108]
It seems the LSP library is still using it's own uri0, and that it is [incomplete](https://github.com/ocaml/ocaml-lsp/blob/master/lsp/src/uri0.ml#L3-L4C18). It'd be very helpful if this module implemented the rest of the spec

**Comment by rgrinberg** [comment]
There's no plans to make this library complete. We only need the subset required for lsp. Is there anything in particular our uri module doesn't handle for you?

**Comment by ajbt200128** [comment]
Right now the main missing functionality I'd appreciate is the query part of a URI. For example any URI with `scheme://path?query` will be trimmed to `scheme://path`.

**Comment by rgrinberg** [comment]
You can try #1125. I don't plan to add full URI support, but if you need anything in particular, make an issue.
