### ISSUE TITLE
Target of DocumentLink should be URI

### ISSUE THREAD

**Issue by Sorokin-Anton** [ocaml/ocaml-lsp#1117]
Currently document link has `target : string option`, but https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/ tells that the target should be `DocumentUri.t option`

It was correct till the merge of `https://github.com/ocaml/ocaml-lsp/pull/827`

**Comment by rgrinberg** [comment]
Indeed. That was a regression. Should be fixed in the next release.
