### ISSUE TITLE
Code actions failures

### ISSUE THREAD

**Issue by giltho** [ocaml/ocaml-lsp#115]
#113 Has introduced a lot of error responses from the server that seem to be happening on codeAction requests (see note from @rgrinberg in the discussion).

**Comment by rgrinberg** [comment]
Some of those errors are expected. For example, when we are doing a destruct call where we don't have a node. For the `invalid_arg`, I guess destruct should be a bit more robust when handling errors.

**Comment by giltho** [comment]
Should we just catch all these errors and return no code action in this case ?

**Comment by rgrinberg** [comment]
I believe so. However that get_every_pattern error should be reported as a bug to merlin. It should handle this error in a more graceful way

**Comment by giltho** [comment]
I'll do that :)

**Comment by giltho** [comment]
Seems like there is already traces of this kind of behaviour (https://github.com/ocaml/merlin/issues/1010 and https://github.com/ocaml/merlin/issues/596)
