### ISSUE TITLE
Batching document change notifications

### ISSUE THREAD

**Issue by jfeser** [ocaml/ocaml-lsp#116]
The emacs lsp-mode package sends a lot of very granular text change notifications (https://github.com/emacs-lsp/lsp-mode/issues/362). Other lsp servers apparently batch these notifications and send diagnostics asynchronously (https://github.com/emacs-lsp/lsp-mode/issues/362#issuecomment-446549480). ocaml-lsp should probably do the same. 

Right now it looks like the type checker runs for every change?

I've looked at implementing this, but I'm not sure how to fit it in with the existing code.

**Comment by giltho** [comment]
This would need an asynchronous server (using lwt or async) we do not have yet.
But in theory yes :)

**Comment by rgrinberg** [comment]
Yes indeed. Although the plan is to use neither Lwt nor Async :)

**Comment by jfeser** [comment]
> neither Lwt nor Async :)

What were you thinking of using? I'd be happy to take a shot at an implementation, but I don't want to make invasive changes that you don't want upstream.

**Comment by rgrinberg** [comment]
I’d like to adopt dune’s fiber library. It’s a much simpler & smaller take on concurrency. Tbh, this is not a project I would recommend a new contributor to take on, but I don’t want to curb anyone’s ambitions ;)

Have a look at dune’s fiber and let me know if you have any questions. If you feel like you can take this on, we can discuss it in private.

**Comment by jfeser** [comment]
I don't see code in the fiber library for doing async io. Is that somewhere else in dune?

**Comment by rgrinberg** [comment]
That is something that is yet to be written. It should be something that isn’t too hard to whip up however. We don’t need anything fancy with libev, spinning up some background threads for reading/writing should be no problem.

**Comment by rgrinberg** [comment]
Anyone who needs this feature can try out this branch: https://github.com/ocaml/ocaml-lsp/pull/181

**Comment by rgrinberg** [comment]
Fixed in master
