### ISSUE TITLE
Can't get project to build

### ISSUE THREAD

**Issue by mrkmndz** [ocaml/ocaml-lsp#12]
Hi All!
I have been using this lsp frontend quite a bit recently, and had been installing it with `opam pin --yes add merlin-lsp.dev https://github.com/ocaml/merlin.git`.
Now that it moved here, I've been trying to get `opam pin --yes add ocaml-lsp-server.dev https://github.com/ocaml/ocaml-lsp.git` to work in the same way, but have been running into several issues.
1. Opam complains about lack of maintainers and synopsis.  I was able to silence that by forking and adding them (https://github.com/mrkmndz/ocaml-lsp/commit/891d86158a5a1329231b888fe3d9ed55b691cdbe)
2. Dune complains about lack of project name. fixed with (https://github.com/mrkmndz/ocaml-lsp/commit/94b18b816d1f70a03ec3ff4f8bb7a92355dc3411)
2. Dune build fails due to "Library "merlin.specific" not found."  Adding merlin as a dependency didn't seem to work, and the only thing that seemed to make it build was to switch to dune 2.0.0 (https://github.com/mrkmndz/ocaml-lsp/commit/78ad2147bdb69625197d74ad49a61cceb80e21ba).  However, this did not feel like the right way to fix it, and causes other problems with my set up.

Furthermore, I can't seem to get it to run once installed in the same way that I used to, namely the form `opam exec  -- ocaml-lsp-server`.

How have you all been running this in development?

**Comment by rgrinberg** [comment]
Thanks for your early interest. Unfortunately, this package isn't yet ready for consumption via opam's pinning workflow. Mostly because we rely on a very specific version of merlin that we obtain via submodules. We now have a readme that details the installation procedure.

Your first two commits look good. Do you mind making PR's for them?

**Comment by andreypopp** [comment]
@mrkmndz this should work now (from the README):
```
$ opam pin add ocaml-lsp-server https://github.com/ocaml/ocaml-lsp.git
$ opam install ocaml-lsp-server
```
