### ISSUE TITLE
Upgrade nag is quite annoying

### ISSUE THREAD

**Issue by Timmmm** [ocaml/ocaml-lsp#1232]
I get this every time I start VSCode... it's quite annoying:

![image](https://github.com/ocaml/ocaml-lsp/assets/376842/d3fc28cf-dd78-458d-8c8c-3e6387031dcc)

I don't care about every minor upgrade. I think there are several things that could be improved here:

1. The extension could just take care of it for me.
2. Failing that, it could add a "click here to install it" button (other extensions do this).
3. It should have a "don't remind me again" button.
4. The hint is wrong. It needs `opam update && ...`

**Comment by copy** [comment]
See https://github.com/ocamllabs/vscode-ocaml-platform/issues/1198
