### ISSUE TITLE
Missing method definitions from LSP 3.17

### ISSUE THREAD

**Issue by ddickstein** [ocaml/ocaml-lsp#1326]
The following definitions are missing - can they be added? It's helpful for the lsp library (and for visibility for missing coverage) even if there aren't accompanying implementations yet.

### Server to client requests
- `workspace/foldingRange/refresh`
- `workspace/inlayHint/refresh`
- `workspace/inlineValue/refresh`

### Client to server requests
- `inlayHint/resolve`
- `textDocument/diagnostic`
- `textDocument/inlineCompletion`
- `textDocument/inlineValue`
- `textDocument/prepareTypeHierarchy`
- `textDocument/rangesFormatting`
- `typeHierarchy/subtypes`
- `typeHierarchy/supertypes`
- `workspace/diagnostic`
- `workspaceSymbol/resolve`

### Client to server notifications
- `notebookDocument/didChange`
- `notebookDocument/didClose`
- `notebookDocument/didOpen`
- `notebookDocument/didSave`

**Comment by rgrinberg** [comment]
Updated some missing types here: https://github.com/ocaml/ocaml-lsp/pull/1332

**Comment by rgrinberg** [comment]
And the server to client requests https://github.com/ocaml/ocaml-lsp/pull/1334

**Comment by rgrinberg** [comment]
All missing methods and notifications are now available.
