### ISSUE TITLE
Option to control inlay hints separately from codelens

### ISSUE THREAD

**Issue by rusty-key** [ocaml/ocaml-lsp#1341]
Hi! 

I see that inlay hints were enabled in the recent release. They are great but might be annoying in some projects, so would be nice to have an option to disable them. But it looks like you can only disable codelens altogether with `ocaml.server.codelens = false` and can't control inlay hints separately. 

Am I missing something or it is impossible indeed? Is it worth adding?

**Comment by rgrinberg** [comment]
Don't we respect inlay hint capabilities?

1. If we do, then your client should pass them correctly.
2. If we don't, then please send a PR to add support.

**Comment by rusty-key** [comment]
My bad, I was looking at how it is implemented in other extensions instead of trying to use editor options. 
```
    "[ocaml]": {
        "editor.inlayHints.enabled": "off"
    }
```
This works perfectly fine ^
