### ISSUE TITLE
Connect ocaml-lsp to Monaco Editor

### ISSUE THREAD

**Issue by chengtie** [ocaml/ocaml-lsp#137]
I want to make a web page that contains an editor of code in OCaml. I prefer to use Monaco Editor. Does anyone know how to connect the Monaco Editor to this ocaml-lsp?

Thank you.

**Comment by rgrinberg** [comment]
Do you have LSP client that you can use? This is the only way to talk to the LSP server.

**Comment by chengtie** [comment]
I want to connect ocaml-lsp to monaco-editor. What LSP client do you recommend?

**Comment by imbsky** [comment]
I think this is popular.
https://github.com/TypeFox/monaco-languageclient

**Comment by chengtie** [comment]
I have made a public repository which contains `monaco-languageclient` and `ocaml-lsp`: https://github.com/chengtie/ocaml-lsp-monaco/tree/730f8e1b8f419bdce71eda707a9e1c462a9d7bc5

The example of `monaco-languageclient` works on the language server of JSON; `ocaml-lsp` works on its test. What we need to do is to connect these two tools.

I really want to make this work, I think it is a very interesting use case of ocaml-lsp and monaco-languageclient.

Developers from monaco-languageclient are asking [questions here](https://github.com/TypeFox/monaco-languageclient/issues/205#issuecomment-609708175). From my understanding, ocaml-lsp communicates with client by stdin/stdout. However, could you tell me how we could "start the server from the command line"?

Thank you.

**Comment by giltho** [comment]
Hi, running `ocamllsp` when it is in your scope should be enough.
If you installed it through opam, `opam exec ocamllsp`
If you just have a binary somewhere, `./path/to/ocamllsp/binary`

**Comment by giltho** [comment]
I'm going to close, please reopen if you still need help
