### ISSUE TITLE
ocamllsp shows "Syntax error" for let expression

### ISSUE THREAD

**Issue by ivnhk** [ocaml/ocaml-lsp#1398]
Hey,

I recently installed `ocamllsp` and started tinkering with OCaml. The problem arose when I typed a let expression with `in` inside:
```
let x = 42 in x + 1
```

Here's the error messages:
<img width="583" alt="image" src="https://github.com/user-attachments/assets/55a6b26b-7092-4cba-9ed2-a0e72239a5bd">

The issue is reproducible in LazyVim and VSCode.

`ocamllsp` version: 1.19.0

If it's a matter of configuration, can you please point me a right direction to fix it?

**Comment by voodoos** [comment]
There is indeed a syntax error in your file:
When using top-level expressions you must separate them from preceding items with `;;`.
The `;;` are optional only before definitions such as `let` (without `in`), `open`, etc.

That was this line [in the manual](https://ocaml.org/manual/5.2/modules.html#module-items) means:

 `module-items ::= { ;; } ( definition ∣ expr ) { { ;; } ( definition ∣ ;; expr) } { ;; } `

**Comment by ivnhk** [comment]
Oh, I got it. Thank you so much and sorry for going straight into the issues

**Comment by voodoos** [comment]
No problem, that's what it's for :-)
