### ISSUE TITLE
Add Azure CI

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml-lsp#14]
This will give us testing on Mac & Windows.

**Comment by c-cube** [comment]
what about the new github-actions, btw?

**Comment by imbsky** [comment]
GitHub Actions is great. The GitHub Actions team is also working on bumping the cache limit now. I definitely recommend it.

**Comment by prometheansacrifice** [comment]
I have a working Azure Pipelines setup from vscode-merlin that I can contribute here. Is everyone onboard with Azure?

**Comment by imbsky** [comment]
Just out of curiosity, We already have Travis and it works well. In many cases, caching is not being used very effectively and I don't think it makes much sense to use Azure. If you want to automate releases, you can do it with Travis, or GitHub Actions without an extra account. Why do you want to use Azure?

**Comment by prometheansacrifice** [comment]
Caching has been working really well on vscode-merlin

**Comment by prometheansacrifice** [comment]
We're seeing ~20min runs despite slow e2e tests

**Comment by imbsky** [comment]
I see. Well, we can also use the caching feature on TravisCI.
https://docs.travis-ci.com/user/caching/

**Comment by imbsky** [comment]
Unless we need to do something that only Azure can do, I don't think we need to force moving.

**Comment by rgrinberg** [comment]
> I have a working Azure Pipelines setup from vscode-merlin that I can contribute here. Is everyone onboard with Azure?

I'm on board.

**Comment by giltho** [comment]
Shall we close this since GH-actions has been merged ?

**Comment by imbsky** [comment]
Yes.
