### ISSUE TITLE
Autocomplete list does not seem to be narrowed on type

### ISSUE THREAD

**Issue by zth** [ocaml/ocaml-lsp#140]
(unsure whether this is the right repo to post this issue on)

When I ask for autocompletion, I get a list of items that seem unrelated/invalid for the thing I'm currently autocompleting. Here's an example:

![image](https://user-images.githubusercontent.com/1457626/78470580-00dcf080-772b-11ea-8599-e73433e05816.png)

I only expect to see `myThing` here since `y` is of type `x` and that's the only thing available on `x`.

This becomes a bit more problematic when multiple language servers (for multiple languages) are active in the same document. Here's an example of that:

![image](https://user-images.githubusercontent.com/1457626/78470665-73e66700-772b-11ea-804c-50d9ee1e55a0.png)
Here's a GraphQL operation defined inside of a string. There's a separate GraphQL language server running and providing autocomplete for that snippet, but its items are pushed to the very bottom of the list by all of the other unrelated/invalid items. Since it's inside of a string I was expecting to get no completion at all from `ocamllsp`/`merlin`. What I was expecting to see was this:
![image](https://user-images.githubusercontent.com/1457626/78470719-b4de7b80-772b-11ea-9bcc-1aa343dc14e6.png)
....which comes from the GraphQL LS, and is indeed available in the list, but at the very bottom. 

So, I guess my question is, is there a way to get rid of the unrelated items and only get a list of things I can actually use in the place where I'm autocompleting?

**Comment by giltho** [comment]
I think this is a merlin issue, because ocaml-lsp calls merlin directly here.

**Comment by zth** [comment]
@giltho ok, thanks! I'll go ahead and post an issue there instead :+1:

**Comment by giltho** [comment]
Please do cite this issue in your merlin issue in case it's actually an ocaml-lsp issue and we need to reopen here :)
