### ISSUE TITLE
Version downgrade to 1.17.0 on 4.14.2

### ISSUE THREAD

**Issue by edwintorok** [ocaml/ocaml-lsp#1405]
opam 2.3.0 wants to do this:
```
opam upgrade
The following actions will be performed:
=== downgrade 1 package
  ↘ ocaml-lsp-server 1.18.0 to 1.17.0
=== upgrade 2 packages
  ↗ jsonrpc          1.18.0 to 1.19.0
  ↗ lsp              1.18.0 to 1.19.0

Proceed with ↘ 1 downgrade and ↗ 2 upgrades? [y/n] y
```

However 1.19.0 of ocaml-lsp-server itself is not available, because that is OCaml 5 only. Should the other packages also have an OCaml version guard?
I don't know why would upgrading those 2 packages require downgrading ocaml-lsp-server though
I mean I can see how upgrading 2 packages at the cost of downgrading one is better, but why is the downgrade needed in the first place?
If you explicitly tell opam to install all at version 1.18.0 it works:
```
opam install ocaml-lsp-server.1.18.0 lsp.1.18.0 jsonrpc.1.18.0
[NOTE] Package jsonrpc is already installed (current version is 1.18.0).
[NOTE] Package lsp is already installed (current version is 1.18.0).
[NOTE] Package ocaml-lsp-server is already installed (current version is 1.18.0)
```

Is this an opam bug, or is there something wrong in the package metadata?

Ah if I ask it to install ocaml-lsp-server 1.18 and upgrade the other 2 it fails with a version constraint error:
```
opam install ocaml-lsp-server.1.18.0 lsp.1.19.0 jsonrpc.1.19.0
[NOTE] Package ocaml-lsp-server is already installed (current version is 1.18.0).
[ERROR] Package conflict!
  * No agreement on the version of lsp:
    - ocaml-lsp-server = 1.18.0 → lsp = 1.18.0
    - lsp >= 1.19.0
```

Perhaps 1.17.0 was missing these constraints.

Metadata on old packages probably needs to be fixed, or (probably simpler) an OCaml version constraints needs to be added on those other 2 packages on 1.19.0

**Comment by voodoos** [comment]
Previous to `1.18.0` the `lsp` and `jsonrpc` packages were vendored so that explains why there no such constriants on 1.17.0. Still, I find it surprising that opam decides to downgrade one package to update 2 others, is that the expected behavior @kit-ty-kate ?

**Comment by voodoos** [comment]
> > Still, I find it surprising that opam decides to downgrade one package to update 2 others, is that the expected behavior ?
> 
> sadly partly yes. It is up to the solver (by default mccs) to decide what's best to do. In this case it has the optimization criteria `-count[version-lag,solution]` which means it's gonna try to reduce the "version-lag" (how far away a given version is from the latest version for this package). In this case, amongst the two solutions there is a winner concerning this criteria:

Very interesting, thank you ! It would probably hard to find a better-in-every-circonstance criteria.. An alternative could be some `--no-downgrade` flag.

Anyway, with the release of `1.20.0-4.14` there is another solution to the issue at hand: upgrade again 🙂
