### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by fopina** [ocaml/ocaml-lsp#1406]
Any plan for a new release? Looking forward to get support for uri fragments (already merged) 😄

**Comment by voodoos** [comment]
I plan to do a release next week 👍

**Comment by voodoos** [comment]
https://github.com/ocaml/opam-repository/pull/26995

**Comment by fopina** [comment]
Did the release go well? I seem to be unable to update the dependency but it might be just me doing something wrong

```
[ERROR] Package conflict!
  * Missing dependency:
    - lsp >= 1.20.0
    no matching version
```

I see the github action of the merge in opam-repository failed, not sure if it was meant to publish things somewhere and failed...

**Comment by fopina** [comment]
I just tried as well with success, thank you for following up 👍
