### ISSUE TITLE
ocamlformat is not listed as a dependency

### ISSUE THREAD

**Issue by yannl35133** [ocaml/ocaml-lsp#141]
It seems that ocamlformat is needed :
```
[Error - 15:51:16] Request textDocument/formatting failed.
  Message: Unable to find ocamlformat binary
  Code: -32600 
[Error - 15:51:16] [lsp] Unable to find ocamlformat binary
```
(VSCode)

This was resolved when I installed it. I think it should be added as a dependency

**Comment by giltho** [comment]
Hi !
This behaviour is intended. `ocamlformat` is not a requirement for the lsp to work, it is only a requirement for the formatting.
However we could probably improve the mmessage to be something like "Please install ocamlformat"

**Comment by rgrinberg** [comment]
> This was resolved when I installed it. I think it should be added as a dependency

That would be a little too strict. ocamlformat is in fact not a dependency for reason projects for example.
