### ISSUE TITLE
Add command to toggle ml/mli files

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml-lsp#144]
The implementation can be trivial initially. Later on we can have something that utilizes dune to understand virtual libraries for example.

**Comment by giltho** [comment]
Hi ! Sorry, I don't fully understand what you mean by "toggle ml/mli files"

**Comment by rgrinberg** [comment]
Yes, I just mean switching between them. It's usually trivial to do in the editor itself, but there are some situations where we need information from the build system.

**Comment by giltho** [comment]
I wrote a [PR for the trivial implementation](https://github.com/reasonml-editor/vscode-reasonml/pull/240) in the old extension but it was right after it went stale.
I don't think there is a way of doing this from the lsp. However, we could hack a command (through [executeCommand](https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand)) that returns, given a file name, the uri of its interface file.
Then, it's up to every editor to call it and implement the switch command themselves.
(Correct me if I'm wrong)

**Comment by rgrinberg** [comment]
That sounds right to me

**Comment by tatchi** [comment]
Hasn't it been implemented in #233 ?

**Comment by smorimoto** [comment]
Yeah.
