### ISSUE TITLE
Fail to `make build/test` ("merlin.query_commands" not found.)

### ISSUE THREAD

**Issue by sebsheep** [ocaml/ocaml-lsp#146]
Hi all!

I try to run the tests, but I have the following error:

```
$ make build
dune build
Done: 0/0 (jobs: 0)  
File "ocaml-lsp-server/src/dune", line 8, characters 16-37:
8 |    merlin.utils merlin.query_commands result yojson ppx_yojson_conv_lib
                    ^^^^^^^^^^^^^^^^^^^^^
Error: Library "merlin.query_commands" not found.
Hint: try: dune external-lib-deps --missing @@default
Makefile:4 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 1
```
I've `opam install merlin`, it is okay, and a naive `opam install merlin.query_commands` complains that 
```[ERROR] Package merlin has no version query_commands.```

What am I missing?

**Comment by giltho** [comment]
Hi ! My best guess would be that you didn't clone recursively.

This should fix your issue hopefully:
```sh
git submodule update --init --recursive
make build
```

**Comment by sebsheep** [comment]
Ok, my initial issue doesn't appear anymore.... But here is what I get now:

```$ make build
dune build
File "_build/.dune/default/vendor/merlin/src/ocaml/utils/dune", line 2, characters 13-25:
2 | (copy_files# 410/*.ml{,i})
                 ^^^^^^^^^^^^
Error: Cannot find directory: vendor/merlin/src/ocaml/utils/410
```

**Comment by giltho** [comment]
You're running ocaml 4.10, with which we are not compatible yet I'm sorry
See https://github.com/ocaml/ocaml-lsp/issues/121

**Comment by giltho** [comment]
I'm assuming this was the expected answer :)
