### ISSUE TITLE
documentHighlight works weird

### ISSUE THREAD

**Issue by Kakadu** [ocaml/ocaml-lsp#147]
For the demo below when I pu cursor somewhere inside `[%expr ....]` LSP gives weird highlighting both in QtCreator and VsCode. We have [the following ](https://gist.github.com/Kakadu/e47801d135ae0356aba17faf7480a3e0) log file. There are a lot of duplicate hightlighting ranges  there. At least we should remove duplicates from there before sending to client.

![qtc-hightlight](https://user-images.githubusercontent.com/438226/78799162-7a424080-79c2-11ea-9c75-f8af34b7213a.png)

![code-hightlight](https://user-images.githubusercontent.com/438226/78799214-86c69900-79c2-11ea-8057-08f32be6db59.png)

```ocaml
open Ppxlib

let loc  = Location.none

let wrap_qml _ x = x


let%test _ =
  wrap_qml [%expr qml singleton ~name:"asdf" ]
    true

let%test _ =
  wrap_qml [%expr qml singleton]
    true

let%test _ =
  wrap_qml
    [%expr qml singleton
      ((author: string) Read getAuthor Write setAuthor Notify authorChanged)
      ((author: string) Read getAuthor Write setAuthor Notify authorChanged)
    ]
    true
```

**Comment by Kakadu** [comment]
It seems that it is related not only to anti quotations (cursor is on line 67)

![qtc-hightlight2](https://user-images.githubusercontent.com/438226/78889338-29872200-7a6c-11ea-8d22-9510e3cb4769.png)

**Comment by Kakadu** [comment]
In two years this issue has become less annoying. But it still present when my own syntax extension is used. I'm not sure, is it an issue with ocaml-lsp-server or with my extension. I created a demo to demostrate this. https://github.com/Kakadu/ocaml-lps-demo-issue147

Could anybody look again and try to locate where the issue is?

**Comment by ulugbekna** [comment]
You can look at merlin tests to see how to run an occurrences query on merlin, e.g., `ocamlmerlin single occurrences -identifier-at 1:11 -filename ./basic.ml < ./basic.ml`. See this https://github.com/ocaml/merlin/tree/master/tests/test-dirs/occurrences 

I don't remember, however, how to make sure merlin takes into account build info, e.g., ppx rewriters

Sorry for incoherent help. I can have a look next week I think

**Comment by voodoos** [comment]
> @voodoos Do you think that it is merlin-related? Or whom should I ping?


It might be related to Merlin, or to the PPX that reports bad location. The first step would be to have a minimal example that could be added to Merlin testsuite. If would be great if you could take the time to prepare one. What we need is:
- a repository with a very simple dune-based project
- the simplest custom ppx possible
- a module (like an executable) using that ppx and where  highlighting is broken.

Once you can notice the issue in vscode you can send me the project and give me the precise line/column where the bad selection happen. That would be very helpful!

**Comment by Kakadu** [comment]
@

> If would be great if you could take the time to prepare one.

@voodoos, I created  PR https://github.com/ocaml/merlin/pull/1469

**Comment by voodoos** [comment]
Closing this issue since it is due to wrong locations in the PPX and not an ocaml-lsp/merlin issue.
