### ISSUE TITLE
Building ocaml-lsp on wsl 

### ISSUE THREAD

**Issue by rexar-fr** [ocaml/ocaml-lsp#150]
I am trying to build the project on WSL environment. 
I got `opm` and `drune` installed on my machine. 
I followed the instruction and here is the error I am getting running `make build`. 

`dune build     
can't open display
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 11
`

**Comment by giltho** [comment]
`Can't open display` looks like a very weird error for dune build. It looks like something is trying to open a GUI inside WSL.
I can't reproduce here, anyone else using WSL can reproduce this ?
Is this still happening ?

**Comment by imbsky** [comment]
I work with native Windows and WSL2, and I have no problems. Are you using WSL1? or WSL2?
