### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by rexar-fr** [ocaml/ocaml-lsp#153]
I am trying to build ocaml-lsp under Ubuntu. 
After following the steps here is the message I get after running `make` 

`File "_build/.dune/default/vendor/merlin/src/ocaml/utils/dune", line 2, characters 13-25:
2 | (copy_files# 410/*.ml{,i})
                 ^^^^^^^^^^^^
Error: Cannot find directory: vendor/merlin/src/ocaml/utils/410
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1
`

**Comment by giltho** [comment]
That's a whole lot of missclicks I made sorry.
You're using 4.10 with which we're not compatible yet I'm sorry. See #121 :)
