### ISSUE TITLE
Installation on Nixos

### ISSUE THREAD

**Issue by DieracDelta** [ocaml/ocaml-lsp#160]
Hello! I'm trying to install this with opam on nixos. I'm on the unstable nixpkgs channel and have opam installed. The commands I've run:

```
opam init
opam pin add ocaml-lsp-server https://github.com/ocaml/ocaml-lsp.git
opam install  -y ocaml-lsp-server
```

And the error I'm getting:
```
File "_build/.dune/default/vendor/merlin/src/ocaml/utils/dune", line 2, characters 13-25:
2 | (copy_files# 410/*.ml{,i})
                 ^^^^^^^^^^^^
Error: Cannot find directory: vendor/merlin/src/ocaml/utils/410
```

Any idea what could be causing this?

**Comment by DieracDelta** [comment]
The solution here is to switch the compiler from 4.10 to 4.09.1. I guess Merlin doesn't support the 4.10 version of the ocaml compiler ?

In any case, this might be worth including in the readme.

**Comment by imbsky** [comment]
The latest Merlin already supports 4.10, but our fork of Merlin doesn't. And a similar issue already exists.

**Comment by imbsky** [comment]
Duplicated with #121.

**Comment by DieracDelta** [comment]
Ah, makes sense. Thanks for the help.

**Comment by imbsky** [comment]
Anytime.
