### ISSUE TITLE
lsp-format with non-ascii char in comment.

### ISSUE THREAD

**Issue by Inkbottle007** [ocaml/ocaml-lsp#161]
`ocaml-lsp` is from April 15. I use it with `emacs` and `lsp-mode`.

Here the initial file, containing a single comment, with non ascii character:
```
$ cat bin/test2.ml 
(* We’ll use *)
```

```
$ cat bin/test2.ml | hd
00000000  28 2a 20 57 65 e2 80 99  6c 6c 20 75 73 65 20 2a  |(* We...ll use *|
00000010  29 0a 0a                                          |)..|
00000013
```

Now we see how `ocamlformat` performs on it:

```
$ ocamlformat bin/test2.ml | hd
00000000  28 2a 20 57 65 e2 80 99  6c 6c 20 75 73 65 20 2a  |(* We...ll use *|
00000010  29 0a                                             |).|
00000012
```

At this point I invoke `lsp-format-buffer` on the file. Here the result:

```
$ cat bin/test2.ml | hd
00000000  28 2a 20 57 65 e2 80 99  6c 75 20 65 20 65 20 2a  |(* We...lu e e *|
00000010  29 0a                                             |).|
00000012
```
It's all mixed up.

Doing that several times did end up with the server crashing, but it might be unrelated.

**Comment by giltho** [comment]
This might be the same root cause as #148

**Comment by giltho** [comment]
@Inkbottle007 would you mind trying again with the last master branch and check if it still happens ?

**Comment by Inkbottle007** [comment]
After `opam upgrade`, it seems I can't reproduce the issue any more.
