### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by yannl35133** [ocaml/ocaml-lsp#166]
Not sure if this is the right repository, or even if you are too early in the development for me to report this, but here goes :
In VSCode,
```ocaml
type compare_op =
| AST_EQUAL         (* e == e *)
| AST_NOT_EQUAL     (* e != e *)
| AST_LESS          (* e < e *)
| AST_LESS_EQUAL    (* e <= e *)
| AST_GREATER       (* e > e *)
| AST_GREATER_EQUAL (* e >= e *)

type t

let compare (op: compare_op) =
  match op with
    | AST_EQUAL
    | AST_NOT_EQUAL
    | AST_LESS
    | AST_LESS_EQUAL
    | AST_GREATER
    | AST_GREATER_EQUAL
```

Issue: when putting the cursor on `AST_EQUAL` (or any other but the last) in `compare`, an error occurs
```
[Error - 01:52:31] Request textDocument/codeAction failed.
  Message: File "vendor/merlin/src/analysis/destruct.ml", line 212, characters 49-55: Assertion failed
  Code: -32603 
[Error - 01:52:31] [lsp] File "vendor/merlin/src/analysis/destruct.ml", line 212, characters 49-55: Assertion failed
```
Other than VSCode complaining about a failed request, this causes no problem.

**Comment by hcarty** [comment]
If it's vscode specific then the issue may be in https://github.com/ocamllabs/vscode-ocaml-platform as well.

**Comment by rgrinberg** [comment]
Don't worry about reporting to the right repository, we'll sort out the issues between the repos. Just keep the good bug reports coming. In this case, this needs to be fixed upstream in merlin. @voodoos is the improved context detection going to fix bugs like this?

**Comment by voodoos** [comment]
I have a slightly different behavior than the one described using VSCode, OCaml Platform 0.1.2 and the latest `ocaml-lsp`. Hovering over any of the constructors gives me the correct hint without error.

However, clicking on one of the pattern matching item triggers it.

More minimal example:
```
type t =
| A | B

let c = function
    | A | B
```
And click on `A` in matching.

My work on context detection won't solve this problem as this is, I guess (@trefis ?), an issue with error recovery, the example code being syntactically incorrect (adding a right hand-side to the matching solves the error).

@rgrinberg What is the extension doing when the pattern is clicked ?

**Comment by trefis** [comment]
> My work on context detection won't solve this problem as this is, I guess (@trefis ?), an issue with error recovery, the example code being syntactically incorrect (adding a right hand-side to the matching solves the error).

To investigate cases like this the `dump` command is often useful (cf `ocamlmerlin single -commands-help`):
```
### `dump -what <source|parsetree|ppxed-source|ppxed-parsetree|env|fullenv|browse|tokens|flags|warnings|exn|paths>`

-what <source|parsetree|ppxed-source|ppxed-parsetree|env|fullenv|browse|tokens|flags|warnings|exn|paths>  Information to dump ()

Not for the casual user, used for debugging merlin
```

On your example:
```
$ ocamlmerlin single dump -what source < /tmp/ulysse.ml | jq .value | sed 's:\\n:\n:g'
"type t =
  | A 
  | B 
let c = function | A|B.[]  -> (([%merlin.hole ])[@merlin.loc ])

"
```
And indeed the `B.[]` looks strange, and this is not a printing bug, the parsetree contains this:
```
            <case>
              pattern (*buffer*[5,35+6]..[5,35+11])
                Ppat_or
                pattern (*buffer*[5,35+6]..[5,35+7])
                  Ppat_construct \"A\" (*buffer*[5,35+6]..[5,35+7])
                  None
                pattern (*buffer*[5,35+10]..[5,35+11])
                  Ppat_open \"\"B\" (*buffer*[5,35+10]..[5,35+11])\"
                  pattern (*buffer*[5,35+10]..[5,35+11])
                    Ppat_construct \"[]\" (*buffer*[5,35+11]..[5,35+11])
                    None
```

The recovery is indeed strange, and might explain the error.
(In any case: your work on context detection will not help here)

**Comment by rgrinberg** [comment]
Interesting. Just curious, what is `[%merlin.hole]` and `[%merlin.loc]`?

**Comment by trefis** [comment]
The first one is a node the parser generates during recovery (when an expression node is needed for instance), the second on is an attribute containing a location that can sometimes be more accurate than the one generated by the parser (but I don't remember in which situation; this is also predates location stacks, so there might not be a real use for it anymore).

**Comment by rgrinberg** [comment]
@yannl35133 could you see if you can reproduce this again? @voodoos fixed a number of bugs in this area. Please re-open if it's still an issue.

**Comment by yannl35133** [comment]
Cannot reproduce anymore indeed. Thanks
