### ISSUE TITLE
OCaml keywords are not suggested.

### ISSUE THREAD

**Issue by mnxn** [ocaml/ocaml-lsp#173]
https://github.com/ocamllabs/vscode-ocaml-platform/issues/183

ocaml-lsp should suggest keywords like language servers for other programming languages. It's particularly annoying when writing `let ... in` expressions as pressing enter at the end of the line completes `in_channel` most of the time.

![image](https://user-images.githubusercontent.com/25037249/81464412-73038380-9176-11ea-8864-eda5326c2418.png)

`Keyword` is already a supported `CompletionItemKind`: https://github.com/ocaml/ocaml-lsp/blob/f3e1f4c543eef14a3cc42bc5efbb41c9137dc3a2/lsp/src/types.mli#L549-L575

I'd imagine that we could maintain a list of keywords for completion, possibly limiting the suggestions based on whether a `.ml` or `.mli` file is open.

**Comment by rgrinberg** [comment]
Yes, this would be nice. I have a WIP PR to add keyword completions to merlin. I should probably revive it soon

**Comment by giltho** [comment]
When finishing a line with `in`, it has become a reflex to type `space -> backspace -> enter` to avoid this...
This would be great :)

**Comment by Kakadu** [comment]
It would be great to add this to 
https://github.com/ocaml/ocaml-lsp/milestone/1

**Comment by rgrinberg** [comment]
Everyone who thumbed up this PR, please give master a test.

**Comment by Kakadu** [comment]
> Everyone who thumbed up this PR, please give master a test.

At the moment I can't do that because of https://github.com/ocaml/ocaml-lsp/issues/291#issuecomment-721293389

**Comment by yannl35133** [comment]
Not sure how that issue affects testing for this test, but I quickly conducted mine and the main complaint (`in` suggestion'ed into `in_channel`) is gone, so fixed for me

**Comment by Kakadu** [comment]
> Not sure how that issue affects testing for this test, but I quickly conducted mine and the main complaint (`in` suggestion'ed into `in_channel`) is gone, so fixed for me

I had issues with invoking completion...

**Comment by rgrinberg** [comment]
The issue has been fixed. Please try again

**Comment by Kakadu** [comment]
It's better now. Thanks!

**Comment by rgrinberg** [comment]
>  I'd imagine that we could maintain a list of keywords for completion, possibly limiting the suggestions based on whether a .ml or .mli file is open.

We need something a little more complex than this. For example, one can include any expression inside a ppx attribute. Luckily, merlin can help us here by letting us filter the list of keywords by the completion context.  @mnxn would you like to take a stab at this?

**Comment by mnxn** [comment]
I'll see what I can do. It might take me a while though, as I'm not familiar with the codebase.

**Comment by rgrinberg** [comment]
Np. I did not assume familiarity and I'm happy to provide any pointers. Something to get you started:

* In merlin's `completion.ml`, consider the `classify_node` function. This function identifies the completion context based on the ast node we're on.

* Then consider the `completion_order` function. This function determines what kind of elements we should suggest based on the completion context above.

We'll likely need to modify the function above to offer a reduced list of keywords based on the context.

**Comment by rgrinberg** [comment]
Fixed in 1.2.0
