### ISSUE TITLE
Explore ways of packaging the dependencies correctly

### ISSUE THREAD

**Issue by giltho** [ocaml/ocaml-lsp#178]
Right now, we're vendoring every dependency.
However, some dependencies may be annoying, like `uri`, because they themselves have widely-used dependencies (in this case `re`), and we don't want to force a `re` user to have a version compatible with `uri` to be able to use the language server.

I have no idea of the current state of the project or even if it could be used, but maybe `duniverse` could be a solution here. Every of ocaml-lsp's dependency is built by dune. That way we could even reduce the amount of libraries we vendor through submodules. @avsm What do you think ? :)

Of course that is one possibility, but we can explore others

**Comment by rgrinberg** [comment]
@tmattio is working on automating installation. Once that is done, this should no longer be a problem.
