### ISSUE TITLE
Better bucklescript setup / workflow

### ISSUE THREAD

**Issue by amiralies** [ocaml/ocaml-lsp#196]
I think current bucklescript setup is not as friendly as it can be.
Installing esy then compiling ocaml and other deps, noisy esy lock / cache files doesn't make sense for me in bucklescript projects.

Is there any plan to improve bucklescript workflow?

**Comment by rgrinberg** [comment]
It's not an immediate goal for me, I'm relying on external contributors for the bucklescript & reason support. @rusty-key last looked at this, he might have an update.

**Comment by rgrinberg** [comment]
I'm closing this because the bucklescript team has their own solution for lsp/vscode. Please direct any questions to them. Thanks!
