### ISSUE TITLE
Unbound module Error

### ISSUE THREAD

**Issue by jeongsoolee09** [ocaml/ocaml-lsp#201]
I am currently working on a project that utilizes Facebook's static analyzer Infer, and getting a lot of `Unbound module xxx` errors where `xxx` can be any modules not built in to the language itself (e.g. Modules created from files in Infer project directories or files that I made myself).

I am almost always ssh'ing to a remote machine. I always use two text editors for all my programming on that machine: Visual Studio Code with [reason-vscode](https://github.com/jaredly/reason-language-server), and Emacs 26 configured with Spacemacs using `ocaml` layer with lsp backend.

On Emacs, I am receiving a lot of 'Unbound module' issues like below.
![image](https://user-images.githubusercontent.com/46663033/84849524-73a20a80-b090-11ea-8e62-73d84fc54a67.png)

The modules marked in blue, i.e. `ProcCfg`, `ProcData`, `Sil`, and `SummaryPayload` are all defined in a file in the Infer project directory, and I am getting `Unbound module` errors for all of them.

However, the interesting thing is,

- Only my Emacs is suffering from this problem. My copy of VSCode recognizes such foreign modules perfectly, and succeeds in delivering Type Inferences and Auto-completion. Before I switched to my current VSC extension I had used another extension called [OCaml and Reason IDE](https://marketplace.visualstudio.com/items?itemName=freebroccolo.reasonml) which uses merlin as backend. This did not suffer from this issue either.
- All the necessary directories are included in the .merlin files with `B` prefixes (though I have not checked them all; there were too many of them).

The `ocaml-lsp` server is installed both on my local and remote machines. They are all `opam switch`ed to a same version.

Could you help me with this issue? Thanks!

**Comment by rosalogia** [comment]
Also running into this problem unfortunately

**Comment by rgrinberg** [comment]
Are you running into this problem in a simpler environment? The main thing that is stopping me from investigating this issue is the lack of a (preferably small) reproducible example.

**Comment by jeongsoolee09** [comment]
Sorry I missed the steps to reproduce this! I was able to witness the same error with the following:

1. ssh to a remote machine
2. create a new directory and `cd` to it
3. create `A.ml` with a function `let say_hi () = print_endline "howdy!"`
4. compile `A.ml` with `ocamlc -o A A.ml`
5. create `B.ml` with
```ocaml
open A

let b = A.say_hi()
```
6. open `B.ml` with Emacs by ssh`ing to the remote with TRAMP
7. Merlin complains that `A` is an unbound module, like below.

![Screen Shot 2020-06-28 at 12 05 17 PM](https://user-images.githubusercontent.com/46663033/85936682-e2585100-b937-11ea-980d-3f3e4eb63bee.png)

**Comment by jeongsoolee09** [comment]
This may be a duplicate of #76 .

**Comment by Khady** [comment]
You don’t have a .merlin file in your example. I am not sure that merlin can detect other modules with this file.

**Comment by rosalogia** [comment]
This was my issue too! Thanks for the help :)

**Comment by jeongsoolee09** [comment]
That is strange, because if I actually open the file from emacs installed my *remote* machine, it tells that there is no error whatsoever (in `B.ml`), even if there is no `.merlin` file in the directory. I guess it's opening the remote file in the remote machine itself vs via TRAMP that is making the difference.

**Comment by giltho** [comment]
I'm closing the issue, please reopen if this was not the actual issue :)
