### ISSUE TITLE
Lost diagnostics after moving from commit b3cc35d to commit c6d6321 with vim-lsp

### ISSUE THREAD

**Issue by xguerin** [ocaml/ocaml-lsp#208]
Hello,

I just noticed that I lost warning/error reports after upgrading to c6d6321 from b3cc35d.

This happens with with vim 8.2 1-1096, neovim v0.5.0-dev (nightly), and vim-lsp HEAD@ 11b1350.

I am not quite sure what do provide to better help diagnosing the issue, but I’d be happy to help as much as I can.

**Comment by giltho** [comment]
Hi @xguerin, which operating system are you using ?

**Comment by xguerin** [comment]
> Hi @xguerin, which operating system are you using ?

I am using Debian Buster.

**Comment by rgrinberg** [comment]
Do you still get auto completion? Or is it just diagnostics that are absent?

**Comment by xguerin** [comment]
@rgrinberg I do indeed still get autocompletion. Only diagnostics are absent.

**Comment by rgrinberg** [comment]
Okay, I can reproduce this. Will try to fix tomorrow.

**Comment by rgrinberg** [comment]
Should be fixed by #211
