### ISSUE TITLE
Merlin update broke LSP features (on windows?)

### ISSUE THREAD

**Issue by mnxn** [ocaml/ocaml-lsp#214]
After commit https://github.com/ocaml/ocaml-lsp/commit/b20c3426c8f4a66cae0e2a8ed2acdf845bb81d1c, the language server does not work with a built dune project.

With a clean project (no `_build`), LSP features work fine for a single modules - not using external modules, which was how it worked before.

However, when building the project (`dune build`) and restarting VSCode, no LSP features work. Here are the logs:
```
Uncaught error when handling notification:
`Assoc ([("params",
          `Assoc ([("textDocument",
                    `Assoc ([("uri",
                              `String ("file:///c%3A/Users/Max/Desktop/hello/bin/main.ml"));
                              ("languageId", `String ("ocaml"));
                              ("version", `Int (1));
                              ("text",
                               `String ("let () = print_endline Hello.str\r\n"))
                              ]))
                    ]));
          ("method", `String ("textDocument/didOpen"));
          ("jsonrpc", `String ("2.0"))])
Error:
[ { exn = "Unix.Unix_error(20, \"create_process\", \"dot-merlin-reader\")"
  ; backtrace =
      "Raised by primitive operation at file \"unix.ml\", line 877, characters 2-62\n\
       Called from file \"vendor/merlin/src/kernel/mconfig_dot.ml\", line 142, characters 16-71\n\
       Called from file \"vendor/merlin/src/kernel/mconfig_dot.ml\", line 166, characters 14-45\n\
       Called from file \"vendor/merlin/src/kernel/mconfig_dot.ml\", line 190, characters 12-45\n\
       Called from file \"vendor/merlin/src/kernel/mconfig.ml\", line 212, characters 24-56\n\
       Called from file \"ocaml-lsp-server/src/document.ml\", line 83, characters 15-63\n\
       Called from file \"ocaml-lsp-server/src/ocaml_lsp_server.ml\", line 645, characters 6-45\n\
       Called from file \"lsp/src/rpc.ml\", line 310, characters 21-50\n\
       Called from file \"vendor/fiber/fiber.ml\", line 110, characters 10-15\n\
       "
  }
]
[Error - 11:44:45 AM] Request textDocument/documentSymbol failed.
  Message: no document found with uri: file:///c%3A/Users/Max/Desktop/hello/bin/main.ml
  Code: -32600 
[Error - 11:44:45 AM] Request textDocument/foldingRange failed.
  Message: no document found with uri: file:///c%3A/Users/Max/Desktop/hello/bin/main.ml
  Code: -32600 
[Error - 11:44:45 AM] Request textDocument/codeLens failed.
  Message: no document found with uri: file:///c%3A/Users/Max/Desktop/hello/bin/main.ml
  Code: -32600 
[Error - 11:44:50 AM] Request textDocument/hover failed.
  Message: no document found with uri: file:///c%3A/Users/Max/Desktop/hello/bin/main.ml
  Code: -32600 
[Error - 11:44:53 AM] Request textDocument/formatting failed.
  Message: no document found with uri: file:///c%3A/Users/Max/Desktop/hello/bin/main.ml
  Code: -32600 
```

I'm using ocamllsp through Cygwin on Windows.

I'm not sure if this is the same problem as #213, as there is no mention of `csexp` with this problem.

**Comment by ulugbekna** [comment]
This seems to have the same source of the problem: reading of `.merlin`. A couple of questions:

1. Where is `main.ml` located in reality? Is the path in the logs (`file:///c%3A/Users/Max/Desktop/hello/bin/main.ml`) correct? (maybe, project structure could be useful?)
2. How does one get logs when running the extension? I don't get logs even with `OCAML_LSP_SERVER_LOG` env variable set (I think vs extension runs the lsp with a clean "opam environment")

**Comment by mnxn** [comment]
1. It is located at `C:\Users\Max\Desktop\hello\bin\main.ml` in terms of the Windows path. Project structure is from `dune init project`, here are the files: https://github.com/mnxn/ocamllsp-merlin-example (I included build artifacts)

2. The language server logs can be found by going to the "OCaml Language Server" output channel in VSCode:
![image](https://user-images.githubusercontent.com/25037249/86496583-f71b5700-bd32-11ea-9eca-7573e320fd9e.png)

**Comment by rgrinberg** [comment]
cc @voodoos

**Comment by rgrinberg** [comment]
Could you try installing the `dot-merlin-reader` package and see if it solves your issue? You should be able to pin it from the merlin repo.

**Comment by voodoos** [comment]
> Could you try installing the `dot-merlin-reader` package and see if it solves your issue? You should be able to pin it from the merlin repo.

Yes, this should work. However you should pin this version:
`opam pin add dot-merlin-reader https://github.com/voodoos/merlin.git#fix-csxep-result`

(a recent `csexp` update prevents master from building)

**Comment by mnxn** [comment]
> Could you try installing the `dot-merlin-reader` package and see if it solves your issue? You should be able to pin it from the merlin repo.

Yes, that seems to fix it.

> (a recent csexp update prevents master from building)

ocaml/merlin master built fine for me.

**Comment by rgrinberg** [comment]
For now, I've reverted the change. Let's wait until dot-merlin-reader is actually released.
