### ISSUE TITLE
Code completion should show documentation.

### ISSUE THREAD

**Issue by mnxn** [ocaml/ocaml-lsp#215]
Language servers for other languages provide documentation on code completion.

Java:
![java](https://user-images.githubusercontent.com/25037249/86500021-2e91ff80-bd43-11ea-88fd-b7a9780c515b.png)

ocamllsp already shows documentation on hover:

![ocaml_hover](https://user-images.githubusercontent.com/25037249/86500042-44072980-bd43-11ea-8410-db30555dc587.png)

The same documentation should be visible on code completion, but it isn't:

![ocaml_compl](https://user-images.githubusercontent.com/25037249/86500058-5d0fda80-bd43-11ea-8f62-222c99217b31.png)

**Comment by rgrinberg** [comment]
It does now. Things aren't ideal as we're fetching it eagerly, but @ulugbekna is working on that.
