### ISSUE TITLE
Can't get ocaml-lsp to detect external modules

### ISSUE THREAD

**Issue by konsolas** [ocaml/ocaml-lsp#232]
I'm going through Real World Ocaml at the moment and I'm having some difficulties getting ocaml-lsp to recognise the Base library.

I have the following source file: (playground.ml)
```
open Base
let three = Float.of_int 3
```
And the following dune file:
```
(executable
  (name playground)
  (libraries base)
)
```
This project compiles and runs with `dune build` without any errors. 

However, ocaml-lsp raises the following issue:
```
1:6   	ocamllsp    	error     	Unbound module Base
```

What do I need to do to get ocaml-lsp to recognise external modules? My editor is Sublime Text 3 and I'm using the [Sublime LSP plugin](https://github.com/sublimelsp/LSP).

**Comment by ulugbekna** [comment]
The likely reason Base is not recognized is that something is wrong with your `.merlin` file. Could you show us your `.merlin` file in the directory where your `dune` and `playground.ml` files are? Also, try maybe running `dune build -w`, which runs the builds in watch-mode, which keeps merlin file up-to-date.

Showing contents of files that I have below.

![image](https://user-images.githubusercontent.com/16353531/89074635-f3eca880-d37c-11ea-996c-78091cfdef07.png)

**Comment by konsolas** [comment]
Hi,

This is my .merlin file:
```
EXCLUDE_QUERY_DIR
B /home/vincent/.opam/4.10.0/lib/base
B /home/vincent/.opam/4.10.0/lib/base/base_internalhash_types
B /home/vincent/.opam/4.10.0/lib/base/caml
B /home/vincent/.opam/4.10.0/lib/base/shadow_stdlib
B /home/vincent/.opam/4.10.0/lib/sexplib0
B /home/vincent/.opam/4.10.0/lib/stdio
B _build/default/.playground.eobjs/byte
S /home/vincent/.opam/4.10.0/lib/base
S /home/vincent/.opam/4.10.0/lib/base/base_internalhash_types
S /home/vincent/.opam/4.10.0/lib/base/caml
S /home/vincent/.opam/4.10.0/lib/base/shadow_stdlib
S /home/vincent/.opam/4.10.0/lib/sexplib0
S /home/vincent/.opam/4.10.0/lib/stdio
S .
FLG -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs
```

I wasn't able to run dune build -w due to a missing dependency on inotifywait, but I ran dune build again so the file should be up to date.

**Comment by ulugbekna** [comment]
Hi. The file looks fine. If even with the updated merlin file you showed us, you still get that error, this is very strange.

**Comment by konsolas** [comment]
It looks like I had the wrong project root directory set in my editor, which is why the `.merlin` file wasn't being found. Thank you for your time.

**Comment by ulugbekna** [comment]
No problem.

Sublime-LSP uses reason-language-server as default for ocaml & reason. Did you configure it yourself? Could you share how you set everything up?

**Comment by konsolas** [comment]
This is the relevant part of my `LSP.sublime-settings` file:

```
{
	"clients":
	{
		"ocaml":
		{
			"command":
			[
				"/home/vincent/start-ocamllsp.sh"
			],
			"enabled": true
		}
	}
}
```

Where `start-ocamllsp.sh` is as follows:
```
#!/bin/bash
eval $(opam env)
ocamllsp
```

I had originally tried to run ocaml-lsp in WSL connected to Sublime-LSP on Windows, but this fails spectacularly since Sublime Text sends Windows paths through the language server protocol.
