### ISSUE TITLE
Unbound module in https://github.com/ocaml/ocaml/blob/4.11.0/parsing/ast_helper.ml

### ISSUE THREAD

**Issue by cmxa** [ocaml/ocaml-lsp#241]
I am using ocaml-lsp under vscode-ocaml-platform. When I perform the following:

```sh
git clone -b 4.11.0 https://github.com/ocaml/ocaml.git
cd ocaml
./configure
make
code . && code parsing/ast_helper.ml
```

I get the error `Unbound module Misc` from ocamllsp on line 33 (no other errors).

**Comment by rgrinberg** [comment]
I think you need to build OCaml with dune so that the correct .merlin files are generated.
