### ISSUE TITLE
ETA on proper ocamllsp opam package

### ISSUE THREAD

**Issue by aryx** [ocaml/ocaml-lsp#243]
I would like to use the lsp/ library in one of my ocaml projects and it would be easier if
it was available as a regular OPAM package instead of having to use opam pin ...
Is there an estimate time of when there will be a propose ocamllsp-server and ocamllsp OPAM package?

**Comment by rgrinberg** [comment]
The release is imminent. We just need `dune-release` to support sources that include git submodules.

**Comment by aryx** [comment]
Fantastic! Thx for all your work! Can't wait to use ocamllsp in my editor.

**Comment by aryx** [comment]
Any update?

**Comment by rgrinberg** [comment]
I've made an issue on the dune-release side https://github.com/ocamllabs/dune-release/issues/279 so all we can do is wait at this point.

What's stopping you from using ocamllsp right now? You can always pin the repository.

**Comment by corwin-of-amber** [comment]
For some reason `opam pin` with the repo url takes *forever* to complete. Anyone else noticed that? Why does it take so long to sync?

**Comment by aryx** [comment]
thx! http://opam.ocaml.org/packages/lsp/

**Comment by smorimoto** [comment]
If you want to install a server, make sure you install `ocaml-lsp-server`. `lsp` is another package.
