### ISSUE TITLE
Trying to do a complex open in OCaml < 4.08 fatal crashes the server

### ISSUE THREAD

**Issue by johnhaley81** [ocaml/ocaml-lsp#244]
👋 

I was editing a file and somehow accidentally tried to create a complex open while I was in the middle of adding my changes. I didn't not intend to use this feature but by accidentally trying to, it brought down the server.

Here's the stack trace:

```
[Error - 1:37:15 PM] Request textDocument/codeAction failed.
  Message: Extend_driver.Extension("reason", "Migrate_parsetree__Migrate_parsetree_def.Migration_error", "File \"QwickioContainers_ActiveShifts_Section_ShiftRows.re\", line 302, characters 4-8: complex open are not supported before OCaml 4.08")
  Code: -32603 
/-----------------------------------------------------------------------
| Internal error: Uncaught exception.
| Extend_driver.Extension("reason", "Migrate_parsetree__Migrate_parsetree_def.Migration_error", "File \"QwickioContainers_ActiveShifts_Section_ShiftRows.re\", line 302, characters 4-8: complex open are not supported before OCaml 4.08")
| Raised at file "vendor/stdune/result.ml" (inlined), line 19, characters 15-22
| Called from file "ocaml-lsp-server/src/document.ml", line 84, characters 2-19
| Called from file "vendor/fiber/fiber.ml", line 187, characters 36-41
| Called from file "vendor/fiber/fiber.ml", line 98, characters 8-15
\-----------------------------------------------------------------------
```

Would it be possible to gracefully handle this situation instead of allowing the server to crash? Maybe just a friendly message to the user? One would expect to not be able to use a feature not available in a previous version but hopefully that doesn't necessitate the server crashing.

Thank you!

**Comment by rgrinberg** [comment]
What's a complex open anyways? @let-def or @nathanrebours perhaps one of you knows?

**Comment by mnxn** [comment]
> What's a complex open anyways?

"complex open" is a `Pexp_open` *missing_feature* here: https://github.com/ocaml-ppx/ocaml-migrate-parsetree/blob/5efccc2c8b0f33564763d7f3394a0b0cc154f5cd/src/migrate_parsetree_def.ml#L80

`Pexp_open` is described as `open M(N).O` here: https://github.com/ocaml-ppx/ocaml-migrate-parsetree/blob/5efccc2c8b0f33564763d7f3394a0b0cc154f5cd/src/migrate_parsetree_def.ml#L44

I believe it refers to _generalized open statements_ introduced in 4.08: https://caml.inria.fr/pub/docs/manual-ocaml/generalizedopens.html

**Comment by johnhaley81** [comment]
I was definitely not trying to do either of those but I accidentally stumbled upon it somehow and it brought down the server.

¯\\\_(ツ)_/¯

**Comment by rgrinberg** [comment]
Which ppx’s are you using?

**Comment by johnhaley81** [comment]
I that particular file it's just the ReasonReact PPX that's built into bucklescript. Throughout the project I'm using:

- ReasonReact
- graphql-ppx
- reformality

The section of code I was editing at the time was inside of something that would have been touched by ReasonReact.

**Comment by rgrinberg** [comment]
We aren't planning to support older versions of OCaml. Sorry.
