### ISSUE TITLE
All type signatures change to _weak upon building

### ISSUE THREAD

**Issue by jordanrmerrick** [ocaml/ocaml-lsp#246]
Building my project using `dune build @install` as well as building single files is causing the types shown in visual studio as some form as `_weak`. For example, a function's type signature went from 

`string -> string` to `_weak230 -> _weak231`. Another example is `?token_source:string -> ?credentials_source:string -> string -> Base.string Async_kernel__Deferred.t` changed to `_weak227 -> _weak228`.

I haven't seen this happen in Emacs when I scroll over these functions see the type signature, so I do not think the causes are the functions themselves. Doesn't happen in utop either if that helps.

**Comment by ulugbekna** [comment]
I haven't observed this behavior for a long time now. Let us know if you can reproduce this with latest release (1.9.1) or master branch.
