### ISSUE TITLE
Reason & 4.11

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml-lsp#247]
Reason gets in the way of easily testing ocaml-lsp and the latest version of OCaml.
We should either disable the tests or remove reason from the test suite altogether.

**Comment by EduardoRFS** [comment]
Reason is working with OCaml 4.11 since day one, and we always have a version working with the new compile before release. If you want to pin the opam version

> https://github.com/facebook/reason/blob/master/reason.opam

**Comment by rgrinberg** [comment]
Pinning is incredibly inconvenient and makes it painful to release ocaml-lsp. The released version in opam is still incompatible with 4.11

**Comment by rgrinberg** [comment]
#287 fixes this issue
