### ISSUE TITLE
Hover information with just the type information

### ISSUE THREAD

**Issue by aryx** [ocaml/ocaml-lsp#251]
I am (ab)using LSP to search for code using type queries. It would be great if ocaml-lsp could be configured so that the
TextDocumentHover would just return the type of the entity under the cursor instead of also the 
doc comments
(I currently modified my own fork of ocaml_lsp_server.ml in format_contents with
      let value =
        match doc with
        | None -> sprintf "%s" typ
        | Some _d -> sprintf "%s" typ

to discard the doc comment), so that the output of TextDocumentHover can be more easily parsed.

Or is there supposed to be another TextDocumentXxx request to get just the type information?

**Comment by ulugbekna** [comment]
It should be quite easy to parse the response for `TextDocumentHover`:

```ocaml
let extract_type (hover_response : string) : string =
  assert (String.length hover_response > 0);
  let has_markdown_support = String.is_prefix hover_response ~prefix:"```" in
  if has_markdown_support then
    (* hover_response has form ```<lang_name>\n<type>\n ... *)
    match String.split_on_char ~sep:'\n' hover_response with
    | _ :: typ :: _ -> typ
    | _ -> failwith "impossible"
  else
    (* hover_response has form <type> | <type>\n... *)
    match String.split_on_char ~sep:'\n' hover_response with
    | typ :: _ -> typ
    | _ -> failwith "impossible"
```

I don't think we'll be able to add such an option to ocaml-lsp-server

**Comment by aryx** [comment]
no, the \n is not good enough to mark the separation because the type itself can contain some \n if the type is long.

**Comment by ulugbekna** [comment]
You're right. I can then only note that in the markdown version of response, the type and doc is separated by `---`.

**Comment by aryx** [comment]
Hmm, cool. How can I force to get the markdown response when I do a request to ocamllsp?

This is the code I used to make the initial request:

let init_request path =
  let capabilities = ClientCapabilities.create () in
  let params = InitializeParams.create
      ~capabilities
      ~rootUri:path
     ~trace:`Verbose
      () in
  let req = Client_request.Initialize params in
  req

  let inc, outc = Unix.open_process server in
  let io = Io.make inc outc in
  let req = init_request "file:///" in
  let id = send_request req io in
  let res = read_response (id, req) io in

...

**Comment by ulugbekna** [comment]
should be something like this
```ocaml
      let hover =
        HoverClientCapabilities.create ~contentFormat:[ MarkupKind.Markdown ] ()
      in
      let textDocument = TextDocumentClientCapabilities.create ~hover () in
      let capabilities = Types.ClientCapabilities.create ~textDocument () in
...
```

**Comment by aryx** [comment]
Great! Thx. I'll close for now and reopen if it does not work.
