### ISSUE TITLE
Record accessor functions that don't exist are offered as completions

### ISSUE THREAD

**Issue by frou** [ocaml/ocaml-lsp#252]
As shown in the screenshot, the first three autocompletion items offered look like accessor functions to pull values out of a record, but after accepting such a completion, we're told that it doesn't exist (both from realtime LSP diagnostics, and an error if running the compiler).

<img width="453" alt="Screenshot 2020-09-30 at 13 12 09" src="https://user-images.githubusercontent.com/172663/94683756-ec1a9780-031e-11eb-99d0-3e8ae8da550f.png">

`dune`:
```text
(executable
 (name main))
```

`main.ml`
```ocaml
module M = struct
  type t =
    { x : int
    ; y : float
    ; z : string }
end

let r : M.t = {x = 1; y = 2.2; z = "hello"}
let _ = M.y r
```

compiler output:
```text
File "main.ml", line 9, characters 8-11:
9 | let _ = M.y r
            ^^^
Error: Unbound value M.y
```

---

`opam list --installed-roots`:
```text
# Packages matching: root
# Name              # Installed # Synopsis
dune                2.7.1       Fast, portable, and opinionated build system
ocaml-base-compiler 4.11.1      Official release 4.11.1
ocaml-lsp-server    ~dev        pinned to version ~dev at git+https://github.com/ocaml/
```

**Comment by ulugbekna** [comment]
I agree this is annoying but probably comes from a case when you want to disambiguate the type of record `r` as in `r.M.x`.

It would be great if merlin (backend of ocaml-lsp) could differentiate between `record.Module.<autocompletion` and `Module.<autocompletion>`.

**Comment by frou** [comment]
Thank you. I notice there's an even easier repro without involving module names at all:

<img width="430" alt="Screenshot 2020-10-01 at 14 32 02" src="https://user-images.githubusercontent.com/172663/94815856-eaba9f00-03f2-11eb-9729-4e27318ab15b.png">

Should this be an issue on the Merlin repo instead of this one?

**Comment by ulugbekna** [comment]
You can repro without module names because the current file is a module that constitutes your environment imo. 

> Should this be an issue on the Merlin repo instead of this one?

Yes. If they fix these cases, we automatically get those fixes.

**Comment by frou** [comment]
Reported here: https://github.com/ocaml/merlin/issues/1183

**Comment by ulugbekna** [comment]
I would include the initial problem you have as well.

**Comment by frou** [comment]
Reopening since a merlin maintainer identified it as a bug specific to ocaml-lsp-server

**Comment by frou** [comment]
Great stuff. Thanks everyone, I appreciate it.
