### ISSUE TITLE
Inconsistent interfaces when depending on opam lsp package

### ISSUE THREAD

**Issue by SquidDev** [ocaml/ocaml-lsp#259]
Now that lsp is on opam (#243), I thought I should switch my project to that. However, attempting to build the project errors with the following message:

```
$ dune build @install
Error: Files $HOME/.opam/4.08.1/lib/lsp/lsp.cmxa
       and $HOME/.opam/4.08.1/lib/uutf/uutf.cmxa
       make inconsistent assumptions over interface Uutf
```

I believe this is because lsp depends on a vendored uutf package, while I depend on several libraries (alcotest, odoc) which in turn depend on opam's version of uutf.

I understand why you want to vendor dependencies for the main language server, but it's definitely less ideal for the lsp library itself. I'm not sure what the appropriate solution is here - the obvious thing to do would be to have lsp as a separate repository without vendored dependencies, and vendor it into this project, but I realise that adds a substantial maintenance burden.

This may fall under the scope of #178, apologies if so!

**Comment by rgrinberg** [comment]
Yes indeed. We should unvendor uutf for the LSP library. I'll send a PR

**Comment by SquidDev** [comment]
Wonderful, thank you!
