### ISSUE TITLE
Issues with filenames with spaces

### ISSUE THREAD

**Issue by rvs314** [ocaml/ocaml-lsp#261]
Hi, this is something I've been trying to work out for a while now, and it may just be a bug in my configuration, but I think it's a problem with ocaml-lsp.

The bug is that the server can't find other modules in a file whose path contains a space character. As an example, if I have the folder `test` with the following files:
- `a.ml` with the contents `let msg = "Hello World"`
- `b.ml` with the contents `let () = print_endline A.msg`
- `dune` with the contents `(executable (name b))`

After building everything, go-to-definition on `A.msg` from `b.ml` works correctly, opening the other file and displaying the correct message. However, renaming the folder from `test` to `te st` causes OCaml-lsp to give an error saying that module `A` does not exist, and go-to-definition on `A.msg` also give an error.

I think this is a problem in ocaml-lsp, because I've tried a few different things and the server seems to be the common denominator. Everything I've tried is running on Debian:
- Emacs' Merlin-mode works correctly, and can find `A.msg`
- Emacs' Eglot cannot find it
- Emacs' LSP-mode cannot find it
- Vim's vim-LSC cannot find it

Both filenames make the following `.merlin` files:

```
EXCLUDE_QUERY_DIR
B _build/default/.b.eobjs/byte
S .
FLG -open Dune__exe -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs
```

Any help/advice would be greatly appreciated

**Comment by ulugbekna** [comment]
In vscode (and maybe other editors), spaces in file URI's are replaced by `"%20"`s. OCaml-lsp stores and operates with such URIs fine, but merlin seems to depend on "real" URIs. 

vscode's position on this is [here](https://github.com/Microsoft/vscode/issues/66825).

The fix is to replace how we handle URIs in  'uri0.ml` to

```ocaml
let t_of_yojson s =
  string_of_yojson s |> String.replace_all ~pattern:"%20" ~with_:" "
```

But this breaks automatic formatting (easy to fix probably).

@rgrinberg do we want to have "%20"s replaced by spaces when handling URIs?

**Comment by rgrinberg** [comment]
> but merlin seems to depend on "real" URIs.

Where does merlin depend on URI’s?
> do we want to have "%20"s replaced by spaces when handling URIs?

Sure. But we shouldn’t accept a fix that breaks automatic formatting. So let’s fix that as well.

**Comment by yannl35133** [comment]
I left an issue on [vscode-ocaml-platform](https://github.com/ocamllabs/vscode-ocaml-platform/issues/422) which seems to be this exact bug. Should I close it?

**Comment by rgrinberg** [comment]
This repo is the more correct place to report this issue. So you can close the other one.

**Comment by rgrinberg** [comment]
Should be fixed in master. Otherwise, please re-open.
