### ISSUE TITLE
Issue: Unable to load compilation data: Unsupported OCaml version

### ISSUE THREAD

**Issue by broerjuang** [ocaml/ocaml-lsp#263]
Hi, I'm getting this error due to no root directory found. However, even the compilation root not found I'm still able to get the inference. Been try to switch the OCaml version but did't succeed. Any workaround to solve this one?

<img width="674" alt="Screen Shot 2020-10-21 at 14 49 21" src="https://user-images.githubusercontent.com/7804066/96689566-c24c1200-13ac-11eb-97cb-0c4ea8fb99ca.png">

Context: I am using coc-nvim

**Comment by rgrinberg** [comment]
The solution likely lies in changing the esy configuration somehow. You should ask them on github or discord for how to do that.
