### ISSUE TITLE
Format hover information with ocamlformat

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml-lsp#301]
Type signatures emitted by hover look a little off when they're long. It would be nice to make them match the style used by ocamlformat.

@voodoos @julow what's the best way to make this happen?

**Comment by Julow** [comment]
OCamlformat can be used as a library. It's not easy to format just a type for now, we could improve this depending on what the desired API is.
Note that OCamlformat has quite a few dependencies.

**Comment by rgrinberg** [comment]
Using it as a library wouldn't be great I think. If ocamlrpc could be invoked via rpc, that would be best.

**Comment by Julow** [comment]
OCamlformat is meant to be executed everytime it is needed (eg. by editors or Dune), would this be too slow in this case ?

**Comment by rgrinberg** [comment]
It would add too much latency on Windows to launch a process for every hover query unfortunately.
