### ISSUE TITLE
strange behavior with type definitions 

### ISSUE THREAD

**Issue by HuStmpHrrr** [ocaml/ocaml-lsp#303]
I find ocaml-lsp doesn't react well to type definitions.

For example, 

```ocaml
type foo = int

let x : foo = 1
```

ocaml-lsp shows `x` has type `int`. while correct, I think it's better to show `foo`.

There are some other occasions, which I cannot find the pattern, where all `int` will replace with `foo`.

I am not sure how challenging is that, but I think is it possible to just keep the type as is, namely not do any expansions or stuff?

**Comment by voodoos** [comment]
I just checked and Merlin with default options does give the expected answer:

```
type foo = int 
let x : foo = 1
    ^^^
    foot
```
```
type foo = int 
let x = 1
    ^^^
    int
```

(https://github.com/ocaml/merlin/pull/1195)

**Comment by rgrinberg** [comment]
@voodoos perhaps you could review our usage of the merlin api here? As far as I can tell, we're doing the same thing merlin is, so I don't know where these differences behavior are coming from.

**Comment by voodoos** [comment]
I will have a look.

**Comment by voodoos** [comment]
I looked at this today and it appears that the issue disappear once the project is built (and thus merlin configuration has been generated). Maybe there is a default configuration for merlin's command line interface that is different than the `Mconfig.initial`  that OCaml-lsp uses.

**Comment by ulugbekna** [comment]
I can't reproduce this with the master branch. Hover over `x` shows `foo` as expected.
