### ISSUE TITLE
[Feature Request] Semantic highlighting 

### ISSUE THREAD

**Issue by hackwaly** [ocaml/ocaml-lsp#326]
As vscode support Semantic highlighting  recently. We'd like to see ocaml-lsp get semantic highlighting feature.

migrate from https://github.com/ocaml/merlin/issues/1094

**Comment by tmattio** [comment]
Related to https://github.com/ocamllabs/vscode-ocaml-platform/issues/432

**Comment by ulugbekna** [comment]
With latest master, you can pass an environment variable `OCAMLLSP_SEMANTIC_HIGHLIGHTING=full` or `OCAMLLSP_SEMANTIC_HIGHLIGHTING=full/delta` to get support for full or (full _and_ delta) semantic tokens support respectively.
