### ISSUE TITLE
How can I debug an issue after updating to 1.3.0

### ISSUE THREAD

**Issue by modlfo** [ocaml/ocaml-lsp#332]
I was using a development version of ocaml-lsp without many problems. After I updated to 1.3.0 seems like ocaml-lsp is not picking my `.merlin` file. 

How can I get logs or debug prints in order to find why my project is not being picked correctly?

**Comment by rgrinberg** [comment]
Could you confirm the version of `dot-merlin-reader` that you have installed?

**Comment by modlfo** [comment]
I have 3.4.2. I kept digging and I believe it could be related to the fact that we have kind of "hack" to integrate Dune along with our build system (cmake based). We don't use the Dune generated .merlin file but a custom one.

Since Dune has improved a lot in more recent versions, I spend some time trying to remove all the workarounds that were in place and get a better integration of Dune with our build system. Now we can use the .merlin files generated by Dune and the extension seems to work correctly.

I will close this issue, but let me know if want more investigation on this issue.
