### ISSUE TITLE
Misplaced error when .merlin file not found

### ISSUE THREAD

**Issue by yannl35133** [ocaml/ocaml-lsp#333]
I recently found out the error message : ``No configuration file found. Try calling `dune build` to generate `.merlin` files.  ocamllsp``

This is a very nice addition, but it is placed at line 2 column 1, which seems odd : why not place it at line 1?
Could you link to the PR which added this, I cannot find it (it is maybe older than I think) ?

Also, two little remarks which are not really worthy of an issue : in CHANGES.md, version 1.2.0, Fixes,
> #245: correctly use mutexes on OpenBSD (#264)

(Why no capital letter for Correctly?)
> Disable non-prefix completion. There's no reliably way to trigger it and it can be slow.

(reliable instead of reliably, no?)

**Comment by yannl35133** [comment]
>Which versions of lsp and dune are you using?

I'm using the latest for both, they are both pinned :
```bash
$ dune-dev --version  # An alias for dune on another switch, the one that I use
2.7.0-370-g5a2e49be6
$ ocamllsp --version
1.3.0-38-g23546b370
```
>That's because the change was done upstream in merlin.

Oh right
>Patches are welcome.

I'm not sure to understand

**Comment by rgrinberg** [comment]
This is no longer relevant. Please re-open if there's still a problem.
