### ISSUE TITLE
trying and failing to format ".ocamlinit" with ocamlformat

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#342]
The vscode ext & ocaml-lsp try to format ".ocamlinit" and fail. See the error message on the screenshot below.

![image](https://user-images.githubusercontent.com/16353531/101452356-6420c180-394f-11eb-9709-88ed3b212c95.png)

This may come from the fact that we treat `.ocamlinit` as an ocaml file (which also causes directives starting with `#` be highlighted as syntax error in a valid `.ocamlinit` file).

**Comment by rgrinberg** [comment]
This should be reported and fixed on the ocamlformat/merlin side. We can't do anything until they support directives.
