### ISSUE TITLE
hover over certain type definitions crashes ocaml-lsp with no stacktrace

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#343]
Hover over a type using a mutually recursive type crashes ocaml-lsp silently (ocaml-lsp usually shows thrown exceptions, but not in this case). Say, we have 

```ocaml
type t = s
and s = string
```

hovering over `s` crashes ocaml-lsp with no stack trace, so maybe segfaulting  🤷‍♂️

---

Other examples of the crash include (but this time the type def itself is not mutually recursive though):

- hover over `t` in `type 'a t = ('a -> unit) -> unit` in `fiber.ml`

---

The issue should be on the ocaml-lsp side [_not_ merlin](https://github.com/ocaml/merlin/issues/1216).

Edit: well, it turned out to actually be merlin (check the link above). Ocaml-lsp however still fails in cases when merlin doesn't.

**Comment by rgrinberg** [comment]
This issue seems to be fixed. I pushed a regression test just in case.
