### ISSUE TITLE
Wrong documentation on hover

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#344]
On hover, I sometimes get documentation for a completely different thing than the identifier I hover over. The "different thing" is usually something that comes from stdlib such as `>` operator or as in the screenshot, where I hover over `err_pos_range` and get correct type but not doc.

![image](https://user-images.githubusercontent.com/16353531/101482455-94c92100-3978-11eb-896c-51c3304f7f9b.png)

(might be a merlin issue, but the last issue found with ocaml-lsp I raised in merlin repo turned out to be ocaml-lsp related, so creating the issue here)

**Comment by tmattio** [comment]
Related to https://github.com/ocamllabs/vscode-ocaml-platform/issues/111

**Comment by ulugbekna** [comment]
That issue could be closed since the problem cannot be fixed on the vscode
extension side.

**Comment by ulugbekna** [comment]
I think I got a reproducible case.

When one types a module name `List`, example : 

```
(* file s.ml *) 
module M = struct 
  let u = () 
  let f = List.<cursor>
end
```

for some reason the documentation on hover at position `p` in file `s.ml` is fetched from the file where `List` is defined, when it should actually fetch the documentation from file `s.ml`. I have only noticed the issue with stdlib modules. 

In the video I need to push the module def down to reproduce the bug, because the `List` module documentation in `list.mli` occurs on lines ~20; hence, we see that the documentation is fetched for things at position `p` from `list.mli` instead of the currently open file.

https://user-images.githubusercontent.com/16353531/109388892-a7297a00-792b-11eb-955a-0b2d6b3f1286.mov

**Comment by ulugbekna** [comment]
This is fixed on master by updating to the latest merlin 4.2

**Comment by rgrinberg** [comment]
@ulugbekna can you make a regression test for this? I'll try and have a look.

**Comment by rgrinberg** [comment]
I'm unable to reproduce this issue with the example above.

**Comment by ulugbekna** [comment]
Sorry, I missed your first message. I'll try to come up with a test. I can
still reproduce it manually though.

**Comment by Sir4ur0n** [comment]
I never know if this kind of message is useful, but just in case: I regularly encounter this problem too, and so do several of my teammates (to confirm this is not an isolated issue for OP).

**Comment by rgrinberg** [comment]
What's blocking me from making progress on this issue is a (preferably small) reproducible test case. Next time you run into this issue, see if you can isolate it.

Rudi.

**Comment by smelc** [comment]
@rgrinberg> Thanks for your awesome work on `ocaml-lsp`. As I'm regularly affected by this issue, I'll keep in mind that a reproduction procedure is welcome.

**Comment by ulugbekna** [comment]
Since the bug is triggered by "pulling in" an stdlib module, for example, for auto-complete (`List.ma<|>`) or hovering over `List.map`, AND after pulling in all consequent requests result in wrong documentation, I think there is some kind of a mutable cache in merlin for documentation or "the current module" cache from which the documentation is extracted.

**Comment by ulugbekna** [comment]
update: I was able to reproduce the bug with any library module (not only stdlib), but the bug still doesn't occur with modules of the project itself, only libraries.

**Comment by ulugbekna** [comment]
Removing [these](https://github.com/ocaml/merlin/blob/08e24475ec498105993a3e47bf032c088fe2e302/src/analysis/locate.ml#L834-L840) lines fixes the issue without regressions on the doc-on-hover tests in merlin.

I could create a PR but I'm having problems with `jq` in merlin test suite, where I keep getting 

```diff
   $ $MERLIN single document -position 7:10 -filename doc.ml < doc.ml |
   > jq '.value'
-  "second function"
+  parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 9, column 1
+  [4]
```

cc @rgrinberg
