### ISSUE TITLE
internal error, uncaught exception: Fiber_unix__Scheduler.Abort(0)

### ISSUE THREAD

**Issue by stephenmell** [ocaml/ocaml-lsp#346]
I'm using `ocaml=4.11.1`, `vscode-ocaml-platform=1.5.1`, and `ocaml-lsp=966a28f5d81b30aac3423e3d723a275057ef092a` (though I had the same issue with `ocaml-lsp=1.3.0`). When starting `ocaml-lsp` (in particular, switching the active sandbox in vscode), I get in the logs:
```
time_mutex: was unlocked
timers_available_mutex: was unlocked
events_mutex: was unlocked
pending events: 0
events: 0
threads: 3
timers: 0
ocamllsp: internal error, uncaught exception:
          Fiber_unix__Scheduler.Abort(0)
          Raised at Fiber_unix__Scheduler.run in file "fiber-unix/src/scheduler.ml", line 388, characters 15-30
          Called from Dune__exe__Ocaml_lsp_server.start in file "ocaml-lsp-server/src/ocaml_lsp_server.ml", line 885, characters 2-307
          Called from Lsp__Logger.with_sections in file "lsp/src/logger.ml", line 155, characters 8-12
          Re-raised at Lsp__Logger.with_sections in file "lsp/src/logger.ml", line 161, characters 4-19
          Called from Lsp__Logger.with_log_file in file "lsp/src/logger.ml", line 187, characters 10-34
          Re-raised at Lsp__Logger.with_log_file in file "lsp/src/logger.ml", line 193, characters 6-21
          Called from Cmdliner_term.app.(fun) in file "ocaml-lsp-server/vendor/cmdliner/src/cmdliner_term.ml", line 25, characters 19-24
          Called from Cmdliner.Term.run in file "ocaml-lsp-server/vendor/cmdliner/src/cmdliner.ml", line 117, characters 32-39
```
Oddly, it then goes on to mostly work (though some things are broken in `vscode-ocaml-platform`, and I'm trying to figure out whether this is the culprit):
```
[Trace - 6:29:09 AM] Sending request 'initialize - (0)'.
Params: {
    "processId": 947858,
    "clientInfo": {
        "name": "vscode",
        "version": "1.51.1"
    },
...
```

**Comment by rgrinberg** [comment]
> When starting ocaml-lsp (in particular, switching the active sandbox in vscode), I get in the logs:

Our shutdown code is a little buggy unfortunately. It should not impact usability however.

> though some things are broken in vscode-ocaml-platform, and I'm trying to figure out whether this is the culprit

Which things are broken exactly?

**Comment by stephenmell** [comment]
> Our shutdown code is a little buggy unfortunately. It should not impact usability however.

Ah, I didn't realize that was during shutdown rather than startup, but that makes sense.

> Which things are broken exactly?

Trying to create a terminal in the current sandbox fails with:
```
Could not open a terminal in the current sandbox. The sandbox may not have loaded yet.
```
But this seems like a `vscode-ocaml-platform` issue, so I can go make an issue there.

**Comment by rgrinberg** [comment]
@mnxn any reason why the terminal could not be opened?

**Comment by mnxn** [comment]
> @mnxn any reason why the terminal could not be opened?

It would only fail if it can't determine the shell path and args: 

https://github.com/ocamllabs/vscode-ocaml-platform/blob/3f00e3d669c78b34655889253077722646cf78a4/src/terminal_sandbox.ml#L66

For some reason, I can only reproduce this on Windows. That error message is always shown unless I set the `ocaml.terminal.shell.windows` setting.

**Comment by stephenmell** [comment]
Lo! If I set `ocaml.terminal.shell.linux` to `/bin/bash`, it works. Here's my [opam package list](https://github.com/ocaml/ocaml-lsp/files/5681893/opam-list.txt). Let me know if there's anything else I can provide that would help with debugging.

**Comment by mnxn** [comment]
Quite strange. The terminal creation used to work without setting `ocaml.terminal.shell`. I wonder if VSCode changed something.

There will have to be a fix or workaround in vscode-ocaml-platform.

**Comment by mnxn** [comment]
@stephenmell: the terminal creation issue is fixed by https://github.com/ocamllabs/vscode-ocaml-platform/pull/484. It was a bug with the extension and unrelated to the fiber abort exception in this issue.

**Comment by rgrinberg** [comment]
I believe this can be closed. Thanks for your reported stephenmell.
