### ISSUE TITLE
Question: ppx_inline_test: extension is disabled because the tests would be ignored

### ISSUE THREAD

**Issue by Kakadu** [ocaml/ocaml-lsp#361]
I get this kind of error in ocaml-lsp + VsCode from time to time and no idea how to fix it or why it happens

>    ppx_inline_test: extension is disabled because the tests would be ignored (the build system didn't pass -inline-test-lib)

Do you have any idea what could cause this? Compilation and testing in  dune is fine, so it should be LSP-related.

To reproduce we need two files: `fopm.ml` and `dune`

```
let%test _ = true

(library
 (name fopm_demo)
 (modules fopm)
 (inline_tests)
 (preprocess
  (pps ppx_inline_test)))
```

**Comment by tcoopman** [comment]
I have the same error with `let%expect_test`

**Comment by Kakadu** [comment]
@tcoopman This should be related 
https://github.com/janestreet/ppx_expect/issues/26
AFAIK this issue should be closed

**Comment by rgrinberg** [comment]
Yes indeed. This isn't an issue with lsp

**Comment by tcoopman** [comment]
Indeed, this project has `ppxlib` 0.20 with the error. An other project has `ppxlib 0.22` and there it works fine. Thanks

Also @rgrinberg I guess this issue is similar to #310? That one can also be closed?

**Comment by rgrinberg** [comment]
Indeed. I closed that one as well.
