### ISSUE TITLE
ocaml-lsp cannot be installed with the latest dune

### ISSUE THREAD

**Issue by barisere** [ocaml/ocaml-lsp#366]
The [current opam lock file](https://github.com/ocaml/ocaml-lsp/blob/cb8aba2238ba5b0e5a6fe0a3180f25077496f75a/ocaml-lsp-server.opam.locked#L31) fixes dune to 2.7.1, but the latest dune is at 2.8.2. Can we update the dependency? I don't know how to do that.

**Comment by tmattio** [comment]
The lock file is only used during the CI/CD, it should not be used to install `ocaml-lsp` with opam. What command are you using?

**Comment by barisere** [comment]
I'm using `opam install ocaml-lsp-server`.

**Comment by barisere** [comment]
@tmattio I was installing the language server using [the old instructions that involved a pin](https://github.com/ocaml/ocaml-lsp/tree/979aab9b8fbff5bf4f80e643fd3d59181c7fc012#opam). I've removed the pin and I've successfully installed from opam. It works. Thank you.
