### ISSUE TITLE
ocaml-lsp-server installation question

### ISSUE THREAD

**Issue by PavelKotov1** [ocaml/ocaml-lsp#368]
I am trying to set up ocaml development environment on VS Code on Debian 9.x
Firstly, I have installed VSCode OCaml Platform

then ran
$ opam pin add ocaml-lsp-server https://github.com/ocaml/ocaml-lsp.git
$ opam install ocaml-lsp-server
the command fails with the message
The following action FAILED
"lambda" build ocaml-lsp-server 1.4.0 

Looks like i have the right versions of prerequisites:
Ocaml toplevel 4.11.1
dune 2.8.2

Thanks in advance!

**Comment by mnxn** [comment]
I'm not sure where the error is coming from but you should install the release version from the opam repository. What you did was install the development version from master.

To remove the pin:
```
opam pin remove ocaml-lsp-server
```
And install the release version:
```
opam install ocaml-lsp-server
```

**Comment by PavelKotov1** [comment]
Dear Max, **from the bottom of my heart: THANKS A LOT!**
That solved my issue and I am ready for more of them!!!
