### ISSUE TITLE
"Unbound module" for all my modules

### ISSUE THREAD

**Issue by TyOverby** [ocaml/ocaml-lsp#369]
I have a project that uses Dune, and I'd like to have ocaml-lsp for use in vscode.  

The dune build works just fine, but for some of the libraries in the project, usage of any module is underlined in red with the text "Unbound module", and likewise for any type or value usage.  This only happens for some of the libraries in this dune project and not others, but they're all quite similar, with no discernable differences.

**Comment by giltho** [comment]
Does this behaviour coincide with you upgrading Dune to 2.8+ ?

I've had some of the same issues, try to clean you `.merlin` files and retry, does that fix it ?

**Comment by TyOverby** [comment]
> I've had some of the same issues, try to clean you .merlin files and retry, does that fix it ?

Amazing, yes, thank you!

**Comment by yankarinRG** [comment]
I have the same problem, using dune 2.8.2 causes Unbound errors while downgrading to 2.7.1 works correctly. Please see my issue on the Visual Studio Platform extension for more details: https://github.com/ocamllabs/vscode-ocaml-platform/issues/532
