### ISSUE TITLE
[PROPOSAL] Separate Jsonrpc Implementation

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml-lsp#37]
JsonRpc is a stand alone & stable protocol. Seems like it would be useful to extract it into its own package.

**Comment by c-cube** [comment]
I have https://github.com/c-cube/jsonrpc2 (functorized over IO, but not too tested), we could possibly merge the two things?

**Comment by rgrinberg** [comment]
What you have seems fine to me. Although you would need to drop support for anything older than 4.06.

**Comment by rgrinberg** [comment]
I don’t think this is such a good idea anymore. Simon’a implementation is already quite good and the version of rpc that lsp uses is non standard. See the business with headers, server sent requests to the client.
