### ISSUE TITLE
"The following libraries are missing in the default context"

### ISSUE THREAD

**Issue by monnier** [ocaml/ocaml-lsp#373]
I'm trying to compile ocaml-lsp from source but am having problems at the very beginning.
The immediate problem is that I get:

```
% dune build ocaml-lsp-server                      
File "ocaml-lsp-server/src/dune", line 9, characters 29-48:
9 |    merlin.utils octavius omd ppx_yojson_conv_lib result stdune yojson))
                                 ^^^^^^^^^^^^^^^^^^^
Error: Library "ppx_yojson_conv_lib" not found.
Hint: try:
  dune external-lib-deps --missing ocaml-lsp-server
Done: 0/0 (jobs: 1)
% dune external-lib-deps --missing ocaml-lsp-server
Done: 0/0 (jobs: 1)Error: The following libraries are missing in the default context:
- csexp
- dune-build-info
- menhirLib
- menhirSdk
- ppx_yojson_conv_lib
Hint: try:
  opam install csexp dune-build-info menhirLib menhirSdk ppx_yojson_conv_lib
% opam install csexp dune-build-info menhirLib menhirSdk ppx_yojson_conv_lib
[NOTE] Package ppx_yojson_conv_lib is already installed (current version is
       v0.14.0).
[NOTE] Package menhirSdk is already installed (current version is 20201216).
[NOTE] Package menhirLib is already installed (current version is 20201216).
[NOTE] Package dune-build-info is already installed (current version is 2.8.2).
[NOTE] Package csexp is already installed (current version is 1.3.2).
% 
```
As you can see, `opam` says the packages are installed, so what does "The following libraries are missing in the default context" mean?

**Comment by smorimoto** [comment]
Are you in the correct switch? Try the following:

```
opam exec -- dune build ocaml-lsp-server  
```

**Comment by monnier** [comment]
> Are you in the correct switch?

I just started using `opam` (as you may have guessed), and AFAIK there's
only one switch: the "default" switch.

> Try the following:
>
> ```
> opam exec -- dune build ocaml-lsp-server  
> ```

That did it, thanks.

[ I guess I should report this problem to the `opam` guys, then.  ]

**Comment by smorimoto** [comment]
Did it work as expected in the way I suggested? If so, I'm guessing that you haven't set the opam hook correctly.

```
A hook can be added to opam's init scripts to ensure that the shell remains in sync with the opam environment when they
are loaded. Set that up? [y/N]
```

"N" is selected by default, so we should carefully read message and select option.

**Comment by monnier** [comment]
This message was vague enough (not sure what "the shell", or "remains in sync", or "they are loaded" means, also the rest of the description seemed to suggest that it was adding a hook to opam's script but to my shell's init scripts) that I chose the N option, indeed.  But I did `eval $(opam env)` as suggested in the shell from which I then ran the above commands, and `printenv` from that shell confirms that `OPAM_SWITCH_PREFIX=/home/monnier/.opam/default`, which I thought is the way to "be in" a particular "opam switch".

**Comment by smorimoto** [comment]
I agree that it's vague. Wouldn't you like to suggest it in the opam repository?

**Comment by rgrinberg** [comment]
Usability wise it's not great, but it's not something that can be addressed in this repository. Closing, but feel free to ask more questions.
