### ISSUE TITLE
Conflict in opam install | wsl 2.0, Ubuntu 20.04, opam 2.0.5, ocaml 4.12.0

### ISSUE THREAD

**Issue by FZed** [ocaml/ocaml-lsp#380]
Hi,
After **opam install ocaml-lsp-server --debug**, I got a conflict :

~$ opam install ocaml-lsp-server  --debug
00:00.003  GSTATE                 LOAD-GLOBAL-STATE @ /home/juju/.opam
00:00.003  RSTATE                 LOAD-REPOSITORY-STATE @ /home/juju/.opam
00:00.183  RSTATE                 Loaded /home/juju/.opam/repo/state.cache in 0.179s
00:00.296  RSTATE                 Cache found
00:00.296  STATE                  LOAD-SWITCH-STATE @ ocaml-base-compiler.4.12.0
00:00.367  STATE                  Detected changed packages (marked for reinstall): {}
00:00.369  STATE                  Switch state loaded in 0.073s
00:00.370  FILE(switch-state)     Wrote /home/juju/.opam/ocaml-base-compiler.4.12.0/.opam-switch/backup/state-20210301084518.export in 0.000s
00:00.500  CLIENT                 INSTALL ocaml-lsp-server
00:00.862  SYSTEM                 [log-595-4bcc67] (in 0.033s) lsb_release -s -r
00:00.877  SYSTEM                 [log-595-ccabea] (in 0.008s) ocamlc -vnum
00:01.086  CLIENT                 **Orphans**: (changes: { ocaml-lsp-server.1.1.0, ocaml-lsp-server.1.2.0, ocaml-lsp-server.1.3.0, ocaml-lsp-server.1.4.0 }, transitive: false) -> full {}, versions {}
00:01.538  SOLVER                 resolve request=install:(ocaml-lsp-server) remove:() upgrade:()
00:02.761  SOLVER                 Load cudf universe (depopts:false, build:true, post:true)
00:02.933  CUDF                   resolve request=install:(ocaml-lsp-server) remove:() upgrade:()
00:02.933  SOLVER                 Calling solver builtin-mccs+glpk with criteria -removed,-count[version-lag,request],-count[version-lag,changed],-changed
00:04.052  CUDF                   Solver call done in 1.119
00:04.960  CLIENT                 **conflict!**
Sorry, no solution found: there seems to be a problem with your request._

Any help greatly appreciated! 
FZed

**Comment by smorimoto** [comment]
4.12.x is not yet supported.

**Comment by FZed** [comment]
Thanks ! That was fast. Have a nice week. When should we expect 4.12 support ?

**Comment by smorimoto** [comment]
There is no clear ETA, but we are already working on it! #377
