### ISSUE TITLE
Support OCaml 4.12.0

### ISSUE THREAD

**Issue by cdisselkoen** [ocaml/ocaml-lsp#381]
Hi,

Apologies if this is already in-progress on a different issue, but I was wondering about support for OCaml 4.12.0 (latest as of this writing, and the default for `opam`, at least on my system for an out-of-the-box install of `opam`).  Merlin seems to already support 4.12.0, so I'm not sure what is keeping `ocaml-lsp-server` from supporting 4.12.0 other than the `ocaml-lsp-server.opam` file, which manually specifies `< 4.12`: https://github.com/ocaml/ocaml-lsp/blob/5df0ce22ce1f24f0ed187cd96c17713c181b0e20/ocaml-lsp-server.opam#L30  

What is required for 4.12.0 support?  I presume it's not just changing the restriction in the `.opam` file?

**Comment by mnxn** [comment]
https://github.com/ocaml/ocaml-lsp/pull/377: 
> Before merging this, we need to update the Merlin fork.

ocaml-lsp uses a [vendored](https://github.com/ocaml/ocaml-lsp/tree/master/ocaml-lsp-server/vendor) merlin fork that has to be updated manually first.

**Comment by cdisselkoen** [comment]
Aha, my bad, I now see there's already an issue.  Closing this in favor of #377, thanks!
