### ISSUE TITLE
Collect request statistics

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocaml-lsp#388]
To improve lsp's performance, we need to have a better understanding which requests are slow, and what is slowing them down. To begin doing this, we need a stats collection mechanism in lsp. We should use dune's `chrome_trace` library to record events for the last N requests served. We could consider adding some custom requests to dump this information somewhere that the user can submit to us.

**Comment by ulugbekna** [comment]
If no one has started working on this, I can give it a shot next week.

**Comment by rgrinberg** [comment]
Sure, just assign it to yourself then.
