### ISSUE TITLE
ocaml-lsp-server 1.5.0 is not available in opam

### ISSUE THREAD

**Issue by fsouza** [ocaml/ocaml-lsp#391]
Hey there, it's great to see that ocaml-lsp 1.5.0 now supports ocaml 4.12, thank you very much for that work!

When I try to install it with opam I still get 1.4.1 though, is that still coming or needs a manual push maybe? :D

**Comment by rgrinberg** [comment]
There's an issue with dune-release that's blocking 1.5.0 unfortunately.

**Comment by rgrinberg** [comment]
It's available thanks to @kit-ty-kate now
