### ISSUE TITLE
Current state of the project

### ISSUE THREAD

**Issue by ShalokShalom** [ocaml/ocaml-lsp#404]
Hi :)

Thanks a lot 

I currently plan to switch to OCaml and I am porting some FSharp code
This is what I got, after 2 other pretty meaningless and misleading messages, is this normal?

![Screenshot_20210404_195241](https://user-images.githubusercontent.com/6344099/113517744-30af1600-9582-11eb-9776-72923fc1141b.png)

**Comment by rgrinberg** [comment]
Syntax errors in OCaml have famously terribly error messages. There's not much we can do I'm afraid.

**Comment by ShalokShalom** [comment]
Should I cry or laugh?

**Comment by mnxn** [comment]
Just to be clear, the emphasis is on the fact that there's not much _we_ can do.

ocaml-lsp does not implement an OCaml parser, so the issue is out of scope for this project. I believe Merlin is doing the parsing here.

**Comment by ShalokShalom** [comment]
Yeah, I thought this is an integration issue on your side since I never thought something like that could possibly the output of the actual engine.
