### ISSUE TITLE
TextDocument.apply_content_change should take a list

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocaml-lsp#41]
the spec doesn't seem to say anything about the order of patches in `DocumentEdit`, so it seems safer to sort them by increasing position (stable sort, to handle the ones with same start pos) and apply them in a `fold_right`? 

this function seems really useful for building any kind of LSP so I think it's good to provide good defaults :)

**Comment by andreypopp** [comment]
I think the order is specified (from LSP spec text):
```
interface DidChangeTextDocumentParams {
        ...

        /**
	 * The actual content changes. The content changes describe single state changes
	 * to the document. So if there are two content changes c1 and c2 for a document
	 * in state S then c1 move the document to S' and c2 to S''.
	 */
	contentChanges: TextDocumentContentChangeEvent[];
}
```
given that description I don't think it's safe to sort by position.

**Comment by c-cube** [comment]
Interesting, I got confused with the `TextEdit` it seems.
