### ISSUE TITLE
lsp: new protocol methods to support?

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocaml-lsp#417]
Interesting things that are newish (3.15 and 3.16 I think):

- progress: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#progress (in particular "work done progress")
- watched file API (https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWatchedFiles

cc @rgrinberg :slightly_smiling_face:

**Comment by rgrinberg** [comment]
> watched file API

I think we already support this.

I'll add some basic support for progress.

**Comment by rgrinberg** [comment]
Master now contains the basics for progress reporting. Give it a try.
