### ISSUE TITLE
Supporting 4.11.1

### ISSUE THREAD

**Issue by SteveBronder** [ocaml/ocaml-lsp#426]
Looking at #369 and https://github.com/ocamllabs/vscode-ocaml-platform/issues/532 it seems like only the current github version will work for the vscode plugin where the github version of lsp server is on 4.12. We need to use [`opam-cross-windows`](https://github.com/ocaml-cross/opam-cross-windows/issues/195) to compile windows binaries which is only up to 4.11.1 so our group is sort of in a weird impasse where we can't update from our current ocaml version to the newer one without breaking either windows compilation or not having type support in vscode.

Is there anything in the lsp server codebase which requires 4.12? Would it be possible to support 4.11.1 with the current develop version of lsp server on github?

**Comment by rgrinberg** [comment]
> Is there anything in the lsp server codebase which requires 4.12? Would it be possible to support 4.11.1 with the current develop version of lsp server on github?

You would need to downgrade the vendored version of merlin to a 4.11 compatible one and make some related (likely small) adjustments in ocamllsp. If you'd like to volunteer to do this, I can help guide you. Regrettably, I don't have enough time to do this myself.

**Comment by rgrinberg** [comment]
I followed the chain of issues until https://github.com/ocaml-cross/opam-cross-windows/issues/195

I think your time will be much better spent on making cross compilation work with 4.12.

**Comment by rgrinberg** [comment]
Closing. The maintainers will not tackle this but will we offer guidance if anyone's interested in doing the work.
