### ISSUE TITLE
[Regression] 1.6.0 GADT bug case

### ISSUE THREAD

**Issue by hackwaly** [ocaml/ocaml-lsp#444]
1.6.0 report type errors
```
This pattern matches values of type [ `B ] t
but a pattern was expected which matches values of type [ `A ] t
Type [ `B ] is not compatible with type [ `A ]
```
```
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
_
```

on this code
```
type 'a t =
  | A : [`A] t
  | B : [`B] t

let f x =
  match x with
  | A -> ()
```
while 1.5.0 doesn't. The ocaml compiler doesn't also.

**Comment by rgrinberg** [comment]
@voodoos is this an issue with merlin as well?

**Comment by voodoos** [comment]
> @voodoos is this an issue with merlin as well?

Yes it does, I added a test in the test suite.

**Comment by voodoos** [comment]
Fixed on merlin master.

**Comment by rgrinberg** [comment]
I've updated merlin so this is now fixed as well. Thanks for the report.
