### ISSUE TITLE
Request textDocument/hover failed. for mutually recursive types

### ISSUE THREAD

**Issue by yannl35133** [ocaml/ocaml-lsp#448]
I have a minimal example where hovering on the second `s` returns the error in title :
```ocaml
type s = unit

and t =
  | A of s
```
My testing indicates that the two types must be mutually recursive but in whichever order.
Using OCaml 4.12.0 and ocamllsp version 1.6.0 on VSCode.

Exact error message :
```
Request textDocument/hover failed.
  Message: uncaught exception
  Code: -32603 
[object Object]
```

**Comment by rgrinberg** [comment]
1.6.1 should fix fix. Please re-open if it doesn't
