### ISSUE TITLE
No config found for file ... in ".". Try calling `dune build`.

### ISSUE THREAD

**Issue by tcoopman** [ocaml/ocaml-lsp#453]
With these dependencies on an `esy` project:

```
{
  "dependencies": {
    "@opam/dune": "^2.8",
    "@opam/ocaml-lsp-server": "1.6.1",
    "@opam/ocamlformat": "0.18.0",
    "ocaml": "4.12.x"
  }
}
```

I get `No config found for file "foo.ml" in ".". Try calling `dune build`.

This is with `neovim` and the build-in lsp. This doesn't seem to happen in vscode so I'm wondering if anyone has an idea on why this would be happening in neovim?

**Comment by tcoopman** [comment]
This was because I forgot to run nvim within an esy sandbox... So `esy nvim .` works

**Comment by jakubrpawlowski** [comment]
I had this issue in vscode using melange. Solution was pinning ocaml-lsp-server to `1.8.3`.

https://github.com/melange-re/melange-basic-template/pull/5
