### ISSUE TITLE
Problems when non-ASCII characters in folder name

### ISSUE THREAD

**Issue by yannl35133** [ocaml/ocaml-lsp#459]
When I have the file structure ("""file contents""") :
```
New
├── dune-project            """(lang dune 2.4)"""
├── lib
│   ├── dune                """(library    (name lib))"""
│   └── lib.ml              """type t"""
└── lib2
    ├── dune                """(library    (name lib2)    (libraries lib))"""
    └── lib2.ml             """type t = Lib.t"""
```
everything works as intended, but when I change `New` to `Néw`, type `Lib.t` becomes unbound in `lib2.ml`. 
When I build with Dune, it compiles fine (as there is no problem)

I have reported this issue before (in the wrong repository, [here](https://github.com/ocamllabs/vscode-ocaml-platform/issues/117)), and it was fixed before; I don't know why it reappeared.

**Comment by ulugbekna** [comment]
Fixed by https://github.com/ocaml/ocaml-lsp/pull/739,  AFAIU

**Comment by yannl35133** [comment]
Can't reproduce
