### ISSUE TITLE
Not handling spaces in parent directory name

### ISSUE THREAD

**Issue by reubenrowe** [ocaml/ocaml-lsp#471]
I've encountered a problem using ocaml-lsp-server via the ocamllabs OCaml Platform VSCode plugin, in which I would get a lot of unbound module errors.

My project involves several libraries, and is compiled with dune. The unbound module errors are being given for modules contained in other libraries within the same project.

I observe this behaviour when my project lives in a directory whose name contains spaces. When I rename the directory so that it does not include spaces, IDE support using the OCaml Platform VSCode plugin works fine.

I'm not sure whether this is a problem with ocaml-lsp-server or with its integration with dune.

**Comment by reubenrowe** [comment]
This is possibly (probably?) related to issue #459 .

**Comment by rgrinberg** [comment]
Please re-open if this still an issue
