### ISSUE TITLE
Problems with renaming a constant inside a module

### ISSUE THREAD

**Issue by jubnzv** [ocaml/ocaml-lsp#486]
I found a few problems when working with the constant defined in the module:

```ocaml
module Config = struct
  let top_stmts = 10
end
```

First two related with renaming, and they are probably just not implemented. But the suggested code action in the third case looks like false positive.

Here are a few gifs with short description that demonstrate the problems:

<details>
  <summary>Renaming 1</summary>

When trying to rename `top_stmts` field, LSP renames the whole `Config.top_stmts`:

![demo](https://user-images.githubusercontent.com/12023585/129140035-201ec6cf-d2d8-450d-b8a5-40ce715b07c4.gif)

</details>

<details>
  <summary>Renaming 2</summary>

The" use " occurrences of the renamed field are not renamed:

![demo11](https://user-images.githubusercontent.com/12023585/129140021-f0c9ebfd-2e91-4272-860f-29addbbd2dca.gif)

</details>

<details>
  <summary>Code action</summary>

The suggested "destruct" code action seems incorrect:

![demo2](https://user-images.githubusercontent.com/12023585/129139492-041dc3ab-63a0-40c7-9fa3-b7cbb31238d7.gif)

</details>

I'm using the `ocaml-lsp` version 1.4.0 installed via `opam`.

Here is the complete source used in the examples:

```ocaml
module Config = struct
  let top_stmts = 10
end

let gen_top_stmts n =
  ()

let () =
  gen_top_stmts Config.top_stmts
```

**Comment by ulugbekna** [comment]
Hi Gregoriy, thank you for the report. 
1. We're aware of `rename`'s deficiencies. 
2. What's incorrect about the destruct though? `Config.top_stmts` is an integer that's being pattern matched into cases `0` and `_`.

**Comment by jubnzv** [comment]
Hi Ulugbek,

> We're aware of rename's deficiencies.
OK, I supposed so, but created this issue, because I cannot find similar issues in the repo.

> Config.top_stmts is an integer that's being pattern matched into cases 0 and _.
Hm, it is a bit irrelevant. But, anyway, this is just a suggested action, not a warning. So, it's okay too.

Thank you for clarifications, I close this then.
