### ISSUE TITLE
failure to parse js_of_ocaml-ppx double hash method accessor

### ISSUE THREAD

**Issue by joprice** [ocaml/ocaml-lsp#492]
When using the js_of_ocaml-ppx `##` method invocation syntax:

```ocaml
let () = Js_of_ocaml.Firebug.console##log "test"
```

I get the following error:

```
[ocamllsp] [E] '##' is not a valid value identifier.
```

Dune successfully compiles the code.

**Comment by rgrinberg** [comment]
Could you try master?

**Comment by joprice** [comment]
I tried with 1.8.3 and I no longer see the error.
