### ISSUE TITLE
Better ocamlformat-rpc intergration

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#495]
Currently, we format code in the hover, we should also be able to 

- [x] format source code (currently, we call `ocamlformat` binary to format source files, which can be avoided if ocamlformat-rpc is installed)
- [x] format generated code:
  - [x] destructed code
  - [x] generated intf code

Other suggestions?

**Comment by rgrinberg** [comment]
What about replacing using ocamlformat-rpc for user format queries when it's available? Currently we still run the binary

**Comment by panglesd** [comment]
I opened PR #549 to fix this issue :)

**Comment by rgrinberg** [comment]
@panglesd I assigned this ticket to you.

**Comment by panglesd** [comment]
Yes, formatting destructed code and generated interface is working when #599 is merged.
