### ISSUE TITLE
OCaml 4.13 support 

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml-lsp#503]
https://github.com/ocaml/merlin/pull/1381 brings support for OCaml 4.13 to merlin.
https://github.com/ocaml/opam-repository/pull/19408 aims at providing a preview package for the early adopters of OCaml 4.13.

I've tried to merge https://github.com/ocaml/merlin/pull/1381 into the ocaml-lsp fork but there are conflicts and it's beyond my understanding. Would it be possible to have a PR somewhere with ocaml-lsp available on OCaml 4.13 so that early adopters can use it too?

cc @rgrinberg @voodoos @ulugbekna

**Comment by daniel-larraz** [comment]
I noticed the latest release of ocaml-lsp-server ([1.9.0](https://opam.ocaml.org/packages/ocaml-lsp-server/ocaml-lsp-server.1.9.0/)) doesn't support OCaml 4.13 yet. Is there a plan when this will happen?

**Comment by ulugbekna** [comment]
Hopefully this week

**Comment by voodoos** [comment]
@ulugbekna I am planning to merge the 413 branch tomorrow at the latest in Merlin master.

**Comment by ulugbekna** [comment]
ocaml-lsp version 1.9.1 with support for ocaml 4.13 is out, so closing.
