### ISSUE TITLE
Diagnostics are played back slowly if didChange events are coming in faster than diagnostics are produced

### ISSUE THREAD

**Issue by copy** [ocaml/ocaml-lsp#504]
Here's a demo:

https://user-images.githubusercontent.com/1816456/132448167-768090e1-86ba-484e-9403-81f2a1e435f5.mp4

lsp clients (e.g. neovim) send `didChange` events on every character (in order to support completion, and since diagnostics are implicit in lsp). ocaml-lsp seems to queue up these events and sends a diagnostic for each of them. If the user types faster than diagnostics are being produced, these delays add up, causing the effect shown in the video.

**Comment by ulugbekna** [comment]
Could you report 
1. ocaml-lsp version
2. client info - which extension and version
3. your OS

ocaml-lsp implements debouncing which should prevent the thing we see on the video; maybe you have file auto-save ON

**Comment by copy** [comment]
1. I've reproduced this in 1.7.0 and 1.8.0
2. neovim with nvim-lspconfig
3. Linux

The plugin does have an option to debounce text changes sent to the lsp server, however that increases the delay I get a diagnostics (for example, after setting the debounce to one second I need to wait up to one second to get the latest diagnostic) and I believe this could be fixed on the ocaml-lsp side.

> ocaml-lsp implements debouncing which should prevent the thing we see on the video; maybe you have file auto-save ON?

What do you mean by file auto-save? I believe lsp clients send `didChange` events on every keystroke by design (to support completion; and because the lsp client doesn't know if the server is working on diagnostics).

It seems that the lsp server calculates exactly one diagnostic per incoming `didChange` event, so perhaps the debouncing is not working correctly?

**Comment by rgrinberg** [comment]
> so perhaps the debouncing is not working correctly?

Could be.

Try increasing the setting to see if it does anything https://github.com/ocaml/ocaml-lsp/blob/master/ocaml-lsp-server/src/configuration.ml#L5

**Comment by copy** [comment]
> Try increasing the setting to see if it does anything https://github.com/ocaml/ocaml-lsp/blob/master/ocaml-lsp-server/src/configuration.ml#L5

Yes, setting it to a higher value fixes the issue, and setting it to 0 makes the issue worse. That said, I prefer the setting of 0 since it reduces the latency before getting diagnostics (if it weren't for the queueing up of diagnostics). Or, in other words, it would be nice if ocaml-lsp could send diagnostics as fast as possible (one at a time), but collapse multiple change events instead of queueing them up.

**Comment by rgrinberg** [comment]
> but collapse multiple change events instead of queueing them up.

It does try to that. The default setting is such that it will wait for 0.25 seconds of editing inactivity before sending the most up to date diagnostic. There's probably a bug here somewhere.

**Comment by rgrinberg** [comment]
Try this patch and see if you're hitting the cancelled branch at all:

```ocaml
diff --git a/ocaml-lsp-server/src/ocaml_lsp_server.ml b/ocaml-lsp-server/src/ocaml_lsp_server.ml
index f671474..d977f35 100644
--- a/ocaml-lsp-server/src/ocaml_lsp_server.ml
+++ b/ocaml-lsp-server/src/ocaml_lsp_server.ml
@@ -168,9 +168,8 @@ let set_diagnostics rpc doc =
           let timer = Document.timer doc in
           let+ res = Scheduler.schedule timer send in
           match res with
-          | Error `Cancelled
-          | Ok () ->
-            ())
+          | Error `Cancelled -> Format.eprintf "cancelled@."
+          | Ok () -> ())
     in
     ()
   in
```

**Comment by copy** [comment]
It does hit the cancelled branch, but less than I would expect. Repeating what I typed in the video above:

```
ok
cancelled
ok
cancelled
ok
cancelled
ok
ok
ok
ok
ok
ok
ok
ok
ok
…
```

**Comment by rgrinberg** [comment]
Could you print Unix.gettimeofday For every ok/cancel and show me what you get? The difference between the ok's should be at least the debounce time.

**Comment by copy** [comment]
Yes, the difference between ok's is bigger than the debounce time (this is with `diagnostics_delay = 0.25`, the previous log was with `diagnostics_delay = 0.0`):

```
00:00:03.997043 ok
00:00:00.001197 cancelled
00:00:00.051944 cancelled
00:00:00.000321 cancelled
00:00:00.069403 cancelled
00:00:00.047868 cancelled
00:00:00.144102 cancelled
00:00:00.000297 cancelled
00:00:00.248861 cancelled
00:00:00.041456 cancelled
00:00:00.071246 cancelled
00:00:00.184572 cancelled
00:00:00.113229 cancelled
00:00:00.186805 cancelled
00:00:00.204764 cancelled
00:00:00.000404 cancelled
00:00:00.114031 cancelled
00:00:00.135216 cancelled
00:00:00.917139 ok
00:00:00.670341 ok
00:00:00.698839 ok
00:00:00.787267 ok
00:00:00.745207 ok
00:00:00.831514 ok
00:00:00.795399 ok
00:00:00.408448 ok
00:00:00.360801 ok
00:00:00.363178 ok
…
```

Note that all entries that follow are ok's until the queueing effect has stopped.

**Comment by rgrinberg** [comment]
Okay, perhaps I have an idea what's going on.

To confirm, could you add a timestamp before this line
```ocaml
          let+ res = Scheduler.schedule timer send in
```

**Comment by rgrinberg** [comment]
Sorry for nuisance, but I'd also like to see some timestamps here:

```diff
diff --git a/ocaml-lsp-server/src/ocaml_lsp_server.ml b/ocaml-lsp-server/src/ocaml_lsp_server.ml
index f671474..855d914 100644
--- a/ocaml-lsp-server/src/ocaml_lsp_server.ml
+++ b/ocaml-lsp-server/src/ocaml_lsp_server.ml
@@ -197,6 +197,7 @@ let set_diagnostics rpc doc =
               { lexing = true; parsing = true; typing = true }
           in
           Document.with_pipeline_exn doc (fun pipeline ->
+              (* here *)
               let errors = Query_commands.dispatch pipeline command in
               let merlin_diagnostics =
                 List.map errors ~f:(fun (error : Loc.error) ->
@@ -247,7 +248,8 @@ let set_diagnostics rpc doc =
               in
               List.append holes_as_err_diags merlin_diagnostics
               |> List.sort ~compare:(fun d1 d2 ->
-                     Range.compare d1.Diagnostic.range d2.Diagnostic.range))
+                     Range.compare d1.Diagnostic.range d2.Diagnostic.range)
+              (* here *))
         in
         Diagnostics.set state.diagnostics (`Merlin (uri, diagnostics));
         Diagnostics.send state.diagnostics)
```

To confirm that the time consumed by merlin is non trivial.

**Comment by copy** [comment]
Sure:

```
00:00:03.796058 schedule ...
00:00:00.312077 Document.with_pipeline_exn begin
00:00:00.557834 Document.with_pipeline_exn end
00:00:00.000066 ok
00:00:00.831686 schedule ...
00:00:00.064203 schedule ...
00:00:00.000035 cancelled
00:00:00.154039 schedule ...
00:00:00.000033 cancelled
00:00:00.000335 schedule ...
00:00:00.000018 cancelled
00:00:00.271854 schedule ...
00:00:00.000031 cancelled
00:00:00.018779 schedule ...
00:00:00.000020 cancelled
00:00:00.067849 schedule ...
00:00:00.000034 cancelled
00:00:00.179250 schedule ...
00:00:00.000048 cancelled
00:00:00.115154 schedule ...
00:00:00.000033 cancelled
00:00:00.260367 schedule ...
00:00:00.000037 cancelled
00:00:00.131017 schedule ...
00:00:00.000035 cancelled
00:00:00.028162 schedule ...
00:00:00.000034 cancelled
00:00:00.327396 Document.with_pipeline_exn begin
00:00:00.378769 Document.with_pipeline_exn end
00:00:00.000039 ok
00:00:00.000340 schedule ...
00:00:00.019257 schedule ...
00:00:00.000037 cancelled
00:00:00.294601 Document.with_pipeline_exn begin
00:00:00.000050 schedule ...
00:00:00.413766 Document.with_pipeline_exn end
00:00:00.000045 ok
00:00:00.000256 Document.with_pipeline_exn begin
00:00:00.000022 schedule ...
00:00:00.347274 Document.with_pipeline_exn end
00:00:00.000038 ok
00:00:00.000267 Document.with_pipeline_exn begin
00:00:00.000072 schedule ...
00:00:00.443465 Document.with_pipeline_exn end
00:00:00.000036 ok
00:00:00.000335 Document.with_pipeline_exn begin
00:00:00.000019 schedule ...
00:00:00.511823 Document.with_pipeline_exn end
00:00:00.000038 ok
00:00:00.000276 Document.with_pipeline_exn begin
00:00:00.000097 schedule ...
00:00:00.566351 Document.with_pipeline_exn end
00:00:00.000034 ok
00:00:00.000307 Document.with_pipeline_exn begin
00:00:00.000020 schedule ...
00:00:00.586907 Document.with_pipeline_exn end
00:00:00.000050 ok
00:00:00.000344 Document.with_pipeline_exn begin
00:00:00.000147 schedule ...
00:00:00.677253 Document.with_pipeline_exn end
00:00:00.000040 ok
00:00:00.000347 Document.with_pipeline_exn begin
00:00:00.000021 schedule ...
00:00:00.684469 Document.with_pipeline_exn end
00:00:00.000043 ok
00:00:00.000288 Document.with_pipeline_exn begin
00:00:00.000020 schedule ...
00:00:00.711074 Document.with_pipeline_exn end
00:00:00.000034 ok
00:00:00.000275 Document.with_pipeline_exn begin
00:00:00.000151 schedule ...
00:00:00.757719 Document.with_pipeline_exn end
00:00:00.000040 ok
00:00:00.000290 Document.with_pipeline_exn begin
00:00:00.000099 schedule ...
00:00:00.822952 Document.with_pipeline_exn end
00:00:00.000052 ok
00:00:00.001334 Document.with_pipeline_exn begin
00:00:00.000065 schedule ...
00:00:00.407869 Document.with_pipeline_exn end
00:00:00.000037 ok
```
