### ISSUE TITLE
PPX won't work after Ocamlformat-rpc starts

### ISSUE THREAD

**Issue by keigoi** [ocaml/ocaml-lsp#513]
Hi! After Ocamlformat-rpc starts (e.g. hovering the cursor over some expression), the following code fails to typecheck at `[%expr 1]` part, saying `Uninterpreted extension 'expr'.`:

```ocaml
open Parsetree

let e = 
  let loc = Location.none in
  [%expr 1]
```
Same for other PPXes. 

Whereas, if I remove ocamlformat-rpc from the opam switch (`opam remove ocamlformat-rpc`), this won't happen.

Versions:
Visual Studio Code 1.60.2 (latest)
OS: macOS 11.2.3

opam switch export:
```
opam-version: "2.0"
compiler: ["ocaml-system.4.12.0"]
roots: [
  "dune.2.9.1"
  "ocaml-lsp-server.1.8.2"
  "ocaml-system.4.12.0"
  "ocamlformat-rpc.0.19.0"
  "ppxlib.0.23.0"
]
installed: [
  "astring.0.8.5"
  "base.v0.14.1"
  "base-bigarray.base"
  "base-bytes.base"
  "base-threads.base"
  "base-unix.base"
  "biniou.1.2.1"
  "cmdliner.1.0.4"
  "cppo.1.6.7"
  "csexp.1.5.1"
  "dot-merlin-reader.4.1"
  "dune.2.9.1"
  "dune-build-info.2.9.1"
  "dune-configurator.2.9.1"
  "easy-format.1.3.2"
  "fix.20201120"
  "fpath.0.7.3"
  "menhir.20210419"
  "menhirLib.20210419"
  "menhirSdk.20210419"
  "ocaml.4.12.0"
  "ocaml-compiler-libs.v0.12.4"
  "ocaml-config.2"
  "ocaml-lsp-server.1.8.2"
  "ocaml-system.4.12.0"
  "ocamlbuild.0.14.0"
  "ocamlfind.1.9.1"
  "ocamlformat-rpc.0.19.0"
  "ocamlformat-rpc-lib.0.18.0"
  "ocp-indent.1.8.1"
  "odoc-parser.0.9.0"
  "pp.1.1.2"
  "ppx_derivers.1.2.1"
  "ppx_yojson_conv_lib.v0.14.0"
  "ppxlib.0.23.0"
  "re.1.10.3"
  "result.1.5"
  "seq.base"
  "sexplib0.v0.14.0"
  "stdio.v0.14.0"
  "stdlib-shims.0.3.0"
  "topkg.1.0.3"
  "uchar.0.0.2"
  "uucp.14.0.0"
  "uuseg.14.0.0"
  "uutf.1.0.2"
  "yojson.1.7.0"
]
```

Best regards

**Comment by keigoi** [comment]
Found a possible root cause. The `system()` call to ppx.exe failes because of ECHILD (`No child processes`) -- because someone is already waiting for the child processes? c.f. https://stackoverflow.com/a/42517274

merlin calling system():
https://github.com/rgrinberg/merlin/blob/c8f45a307798d2f3da86c9ded85f82a3e2d80342/src/ocaml/driver/pparse.ml#L59

And probably the cause is here the `Scheduler` using `Unix.wait` (invoked right after starting Ocamlformat?) always waiting for arbitrary child processes:
https://github.com/ocaml/ocaml-lsp/blob/55bed38ffa3dcdc19bb38597099315369a32bc3e/fiber-unix/src/scheduler.ml#L342

**Comment by keigoi** [comment]
Related (possibly): #492

**Comment by hcarty** [comment]
Thank you for reporting this @keigoi! I installed `ocamlformat-rpc` recently on my machine and ppx handling broke in my vscode setup. I'd made several other changes and missed the connection between the two events.

`opam remove ocamlformat-rpc` and a restart of the language server - not sure if the restart was strictly required - fixed the issue for me.
