### ISSUE TITLE
 go-to-definition is broken

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml-lsp#520]
I tried it with a minmal example, the lens works but the go-to-definition breaks (non-terminating)
My version is 4.10.2 on M1, the plugin is the latest
<img width="1018" alt="Screen Shot 2021-10-13 at 2 53 45 PM" src="https://user-images.githubusercontent.com/747051/137082534-5a44db31-68b1-4036-a75b-0700b60cef3f.png">
)

**Comment by rgrinberg** [comment]
The latest version of the lsp server only works with 4.12. Are you sure that's what you're using?

**Comment by rgrinberg** [comment]
I tried your example and it seems to work. Going to the definition of `List.length` works fine. So is going to the definition of `f` when I jump to it from some other identifier. Do you see any errors in the output pane perhaps?

**Comment by bobzhang** [comment]
go-to-declaration actually works, but go-to-definition gets stuck forever

**Comment by rgrinberg** [comment]
Could you paste a backtrace for me if you don't mind? E.g. `lldb -n ocamllsp -o "bt all"`

**Comment by bobzhang** [comment]
The dune file is very simple, it is generated by `dune init lib hello`

**Comment by mimoo** [comment]
btw you don't seem to use OCaml Platform, is this why this doesn't work? My go-to definition stopped working today and I fixed it by manually choosing my switch there:
<img width="1450" alt="Screen Shot 2021-10-21 at 11 49 29 AM" src="https://user-images.githubusercontent.com/1316043/138342424-35a620ae-2f95-493d-99ca-396029c02c49.png">

**Comment by bobzhang** [comment]
@mimoo I tried several global switches today, none of them worked

**Comment by bobzhang** [comment]
<img width="265" alt="Screen Shot 2021-11-04 at 9 33 06 PM" src="https://user-images.githubusercontent.com/747051/140322428-6050e7bd-23aa-4600-8c32-27138ecfd936.png">

@rgrinberg the pic shows the loading forever, any way I can get some more detailed logs to help diagnose?

**Comment by ulugbekna** [comment]
Please see the vscode-ocaml-platform GitHub page for more information on
debugging and reporting problems

**Comment by rgrinberg** [comment]
Shapes should have fixed this.
