### ISSUE TITLE
Feature Request: More folding!

### ISSUE THREAD

**Issue by cdaringe** [ocaml/ocaml-lsp#547]
# Problem

Only a few things fold!

# Discussion

Let's fold _more_! It's quite common in ocaml for fn authors to inline all sorts of foldable _stuff_ inside fns. fns in fns in fns! 

Specifically, I desire support of `let ... in` expressions. Unsure about `and`. I don't see a lot of `and` out in the wild, besides in the stdlib.

![image](https://user-images.githubusercontent.com/1003261/140658303-afbaef0b-bd8d-4b02-bbac-9850da5bfa6d.png)

Seems like [a](https://github.com/ocaml/ocaml-lsp/blob/16ece09d6dc6af32b9d48dfa095cd5b249ce2162/lsp/src/types.mli#L234) & [b](https://github.com/ocaml/ocaml-lsp/blob/e58630b1077a3b5f9442993756cf2bc5d11bfa41/ocaml-lsp-server/src/ocaml_lsp_server.ml#L590) are relevant here 🤔

**Comment by ulugbekna** [comment]
That's vscode right? Set `folding` to `indentation` in your vscode settings :-) 

![image](https://user-images.githubusercontent.com/16353531/140658648-0e475aba-4ee5-456d-b553-2534d8eeaca8.png)
![image](https://user-images.githubusercontent.com/16353531/140658690-583e5343-d87c-4d65-b805-cd5e2d5d4edb.png)

I'm hesitant about closing this issue, since we could improve folding support in ocaml-lsp as well.

**Comment by cdaringe** [comment]
Yes, I did consider indentation as well. It felt less precise, breaking at non-logically grouped blocks

**Comment by rgrinberg** [comment]
Feel free to send a PR. It should be enough to traverse the let bindings and inspect their locations to generate the folds.

**Comment by tatchi** [comment]
Hey, I quickly looked at that issue and noticed that what we can back from Merlin outline request only contains the "top level bindings". For instance, the following code:

```ocaml
let a =
  let b =
    let i = 6 in
    let () = print_endline "hello" in
    let result = i + 1 in
    result
  in
  let c = b + 3 in
  c
```

produces:

```json
{
  "class": "return",
  "value": [
    {
      "start": {
        "line": 1,
        "col": 0
      },
      "end": {
        "line": 9,
        "col": 3
      },
      "name": "a",
      "kind": "Value",
      "type": "int",
      "children": [],
      "deprecated": false
    }
  ],
  "notifications": [],
  "timing": {
    "clock": 3,
    "cpu": 3,
    "query": 0,
    "pp": 0,
    "reader": 1,
    "ppx": 0,
    "typer": 2,
    "error": 0
  }
}
```

I would have expected the `children` property not to be empty. Do I miss something?

**Comment by tatchi** [comment]
Repro: https://gitpod.io/#https://github.com/tatchi/outline-repro

**Comment by ulugbekna** [comment]
Outline specifically checks only toplevel bindings

Ulugbek

**Comment by tatchi** [comment]
Oh, I see thanks. What would be the best way to implement that feature if we can't use the `outline` command? I see that we should be able through Merlin to get the `parsetree` value of a document. 

Would that be a solution?

**Comment by ulugbekna** [comment]
I think we could traverse the parse tree and collect all locations that we'd like to be able to fold. 

```ocaml
Document.with_pipeline_exn doc (fun pipeline -> 
  let parsetree = Mpipeline.reader_parsetree pipeline in 
  fold_over_parsetree parsetree
```

where `fold_over_parsetree` would traverse and collect fold information. One can use `Ast_iterator` perhaps to fold over the tree with convenience or write their own fold.

("fold" in "folding over tree" is as in "List.fold" over a list rather than code folding)

**Comment by rgrinberg** [comment]
> I see that we should be able through Merlin to get the parsetree value of a document.

It would be a very good solution. As it would also enable folding when the source file isn't well typed.

**Comment by tatchi** [comment]
Nice, thanks for the clarifications. I see better how we should approach it now 🤩

Happy to pick this one up once I've finished the current tasks I'm working on.

**Comment by rgrinberg** [comment]
@cdaringe can you try master? the folds should be more to your liking now.
