### ISSUE TITLE
Search for a symbol in workspace looks into .pp.ml files

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#548]
Searching for a symbol in workspace uses `.pp.ml` files, it seems, which users can't actually open. 

![image](https://user-images.githubusercontent.com/16353531/141314117-c895a71e-c4f0-463b-bf74-d3f39f1cf450.png)

**Comment by tatchi** [comment]
Am I right that `.pp.ml` files are related to `ppxes`? What should be done in that case?

We can filter out `sourcefiles` that end with `.pp.ml` from the result but in that case and given that I understand it correctly, we'll lose symbols from files that are preprocessed by a ppx. Is that acceptable?

**Comment by tatchi** [comment]
I stumbled upon that PR in the merlin repo which seems to be related to the same issue: https://github.com/ocaml/merlin/pull/1219

The proposed fix looks pretty easy and consist of falling back to a corresponding `.ml/.mli` file. According to [this comment](https://github.com/ocaml/merlin/pull/1219#issuecomment-823142961), locations should be preserved.

I got curious and tried that solution. It seems to show good results:

https://user-images.githubusercontent.com/5595092/143181317-40e2c046-317c-469b-87d5-d305e177652b.mov

**Comment by tatchi** [comment]
The fix has been merged upstream and is included in merlin 4.5 https://github.com/ocaml/merlin/pull/1219

I know that there's an ongoing effort to unvendor Merlin so I assume that when that's done, we will have an up to date version of Merlin that contains the fix ? cc @rgrinberg

**Comment by rgrinberg** [comment]
We don't plan to unvendor merlin. Once I will update our fork of it, the fix should be included.

**Comment by tmattio** [comment]
> We don't plan to unvendor merlin.

I thought we agreed that was the plan though?

The fork is making a lot of people's life more difficult, and merlin maintainers have agreed to upstream the patches in principle.

**Comment by rgrinberg** [comment]
I remember agreeing about reducing the patches but certainly not un vendoring merlin.

The difficulties imposed by the fork can be solved by deleting the vendored directory once all the patches are upstreamed.

**Comment by rgrinberg** [comment]
Exactly

**Comment by tatchi** [comment]
> The fix has been merged upstream and is included in merlin 4.5 [ocaml/merlin#1219](https://github.com/ocaml/merlin/pull/1219)

I think I've been confused. I don't think the upstream change would have fixed that issue (at least without any changes from our side). Anyway, good news is that https://github.com/ocaml/ocaml-lsp/pull/671 should fix the issue 🤗

**Comment by tatchi** [comment]
Closed #671
