### ISSUE TITLE
automatically detect code changes rather than requiring an external rebuild

### ISSUE THREAD

**Issue by medovina** [ocaml/ocaml-lsp#558]
The vscode-ocaml-platform documentation says

> Important note: OCaml Language Server has its information about the files from the last time your built your project.
Caveat 1: Because of the note above, during active development of your project, we advise building your project with dune in a polling mode using the option --watch. This rebuilds your project whenever a file is changed in your project. 

That's a bother.  LSP servers for most languages don't work like that - instead, they automatically detect changes as the user types, and recompile type information on the fly.  Why should OCaml be any different?

**Comment by rgrinberg** [comment]
> LSP servers for most languages don't work like that - instead, they automatically detect changes as the user types, and recompile type information on the fly.

Which LSP servers are you familiar with? It's a requirement for C++.

> Why should OCaml be any different?

It cannot work in any other way. Ocamllsp doesn't know how your project is compiled and it needs some of these compiled artifacts to provide the functionality.

**Comment by medovina** [comment]
> > LSP servers for most languages don't work like that - instead, they automatically detect changes as the user types, and recompile type information on the fly.
> 
> Which LSP servers are you familiar with? It's a requirement for C++.

For example, the LSP servers for Python and Haskell automatically update type information as I make changes, without requiring me to perform an external compilation step or even save my source file.

> > Why should OCaml be any different?
> 
> It cannot work in any other way. Ocamllsp doesn't know how your project is compiled and it needs some of these compiled artifacts to provide the functionality.

Of course it could work in a different way.  For example, if the LSP server had an embedded OCaml compiler, it could notice changes on the fly and incrementally recompile to update the type information in memory.

What you're really saying is that this functionality would require major architectural changes and/or be difficult to implement.  OK - I can accept that.  But we shouldn't believe that this change would be impossible.
