### ISSUE TITLE
"Uninterpreted extension 'bind'" - installed with esy in Windows

### ISSUE THREAD

**Issue by travv0** [ocaml/ocaml-lsp#586]
I have an esy project that builds and runs fine, and works with ocaml-lsp under linux/macOS, but when I'm using VS Code in Windows it doesn't seem to process any ppx directives at all (or at least ppx_let and ppx_deriving_yojson). Everything worked fine before I added the ppx dependencies. I'm very new to OCaml, so there's a good chance I just have something configured incorrectly, but the project in question is https://github.com/travv0/vbu.ml. Let me know if any logs or anything would be useful.

**Comment by rgrinberg** [comment]
Are you using the latest version of ocamllsp?

**Comment by travv0** [comment]
I'm using version 1.9.1.

**Comment by rgrinberg** [comment]
Try it again with master.

**Comment by travv0** [comment]
Seems to be working with master, thanks!
