### ISSUE TITLE
Not identifying OUnit2 after switching to OCaml 4.13.1

### ISSUE THREAD

**Issue by gamburgm** [ocaml/ocaml-lsp#592]
# What

After switching to OCaml 4.13.1:

<img width="813" alt="ounit2_error" src="https://user-images.githubusercontent.com/33709622/151098433-2c06f185-2e91-4353-b0ea-b9473bda086c.PNG">

# Reproducing

I was able to reproduce this on both WSL Ubuntu 20.04 LTS and Manjaro 5.10.15.

```
opam switch create 4.13.1
opam install ocamlfind
opam install ounit2
opam install ocaml-lsp-server
```

Additionally installing `merlin` doesn't make any difference.

My `.merlin` file:

```
PKG ounit2
B _build/**
```

My `Makefile`:
```
test: tests.ml
  ocamlfind ocamlc -o test -package ounit2 -linkpkg -g tests.ml
```

Let me know if any additional information would be useful.

**Comment by rgrinberg** [comment]
Hello,

.merlin files are completely ignored by lsp and you must build your project with dune.

**Comment by gamburgm** [comment]
Fix: switch to `4.11.0` instead.

Is there some incompatibility with `ocaml-lsp` and the later versions of OCaml?

**Comment by rgrinberg** [comment]
No, but earlier versions of ocamllsp support .merlin files and older versions of OCaml. So your workaround should work.

**Comment by gamburgm** [comment]
Ah I see, thanks!
