### ISSUE TITLE
OCaml 4.14 support

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml-lsp#595]
This is just an issue to keep track of the progress on the port of ocaml-lsp-server to OCaml 4.14

There is currently a preview package available on opam-repository:
- https://github.com/ocaml/opam-repository/pull/20576

pointing to the following branch: https://github.com/ocaml/ocaml-lsp/compare/master...kit-ty-kate:414
This branch is a simple git submodule update of the merlin vendor to point to: https://github.com/rgrinberg/merlin/commits/414

Users can simply install the preview package using: `opam install ocaml-lsp-server` in an OCaml 4.14 switch.

**Comment by aresbit** [comment]
[ERROR] Could not synchronize /home/aresyang/.opam/cs3110/.opam-switch/sources/ocaml-lsp-server.1.9.2~4.14preview from
        "git+https://github.com/kit-ty-kate/ocaml-lsp.git#414":
        "/usr/bin/git fetch -q" exited with code 128
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocaml-lsp-server.1.9.2~4.14preview

what happen? plz help me , thanks

**Comment by aresbit** [comment]
you means this info? : wsl2 ubantu20
aresyang@LAPTOP-MOGSN96P:~$ opam install ocaml-lsp-server
The following actions will be performed:
  ∗ install ocaml-lsp-server 1.9.2~4.14preview

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] Could not synchronize /home/aresyang/.opam/cs3110/.opam-switch/sources/ocaml-lsp-server.1.9.2~4.14preview from
        "git+https://github.com/kit-ty-kate/ocaml-lsp.git#414":
        "/usr/bin/git fetch -q" exited with code 128
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocaml-lsp-server.1.9.2~4.14preview

**Comment by kit-ty-kate** [comment]
oh code 128! Do you not have git installed? It's required to get this specific package

**Comment by aresbit** [comment]
I am sure that I installed git , maybe  GFW's reason?
aresyang@LAPTOP-MOGSN96P:~$ git --version
git version 2.25.1

**Comment by ulugbekna** [comment]
@rgrinberg released 1.10.6 which supports 4.14 🙂
