### ISSUE TITLE
make install not working

### ISSUE THREAD

**Issue by fjagiell** [ocaml/ocaml-lsp#625]
I am trying to get OCaml onto my VS code. I followed their instructions in the Visual Studio Marketplace, where I was directed to install the OCaml LSP. The commands for opam and esy don't work so I followed the instructions under source. The the first two steps work fine but the final one with the command "make install" won't work. VS Code tells me that the make command was not found. Is there anything I can do to fix this?

**Comment by ulugbekna** [comment]
> The commands for opam and esy don't work

What error do you get? In what way don't they work? 

> VS Code tells me that the make command was not found. Is there anything I can do to fix this?

If `make` command is not found, then you need to install `make` using your system package manager -- for example, `brew` if you're on Mac or `apt-get` if you're on linux

**Comment by fjagiell** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/46580428/154325913-e26964a0-e84e-423e-9732-32de6f7e317e.png">

The same error occurs with all three.

**Comment by ulugbekna** [comment]
You need to install those tools to run them.

**Comment by fjagiell** [comment]
I did have opam installed yet it still wasn't working. I found a way to be able to use the tools outside of VS code but this was not really resolved.
