### ISSUE TITLE
failed to opam install ocaml-lsp-server with ocaml4.14

### ISSUE THREAD

**Issue by aresbit** [ocaml/ocaml-lsp#648]
aresyang@LAPTOP-MOGSN96P:~/myleetcode$ opam install ocaml-lsp-server
The following actions will be performed:
  ∗ install ocaml-lsp-server 1.9.2~4.14preview

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] Could not synchronize /home/aresyang/.opam/cs3110/.opam-switch/sources/ocaml-lsp-server.1.9.2~4.14preview from
        "git+https://github.com/kit-ty-kate/ocaml-lsp.git#414":
        "/usr/bin/git fetch -q" exited with code 128
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocaml-lsp-server.1.9.2~4.14preview

**Comment by ulugbekna** [comment]
Should be fixed by latest release - 1.10.6 :-)
