### ISSUE TITLE
Workspace symbols have wrong file paths

### ISSUE THREAD

**Issue by artempyanykh** [ocaml/ocaml-lsp#656]
Repro: 

```
git clone git@github.com:ocaml/ocaml.git
./configure
dune build @libs
```

1. Open in VSCode
2. Go to symbol in workspace
3. Type 'ulambda' 
4. The list has an item in `clambda.ml`, but opening it fails with 'File not found'. 

The response from LSP indeed returns just `clambda.ml` instead of `middle_end/clambda.ml`:
```
[Trace - 21:56:41] Received response 'workspace/symbol - (82)' in 503ms.
Result: [
    {
        "name": "ulambda_switch",
        "kind": 15,
        "deprecated": false,
        "location": {
            "uri": "file:///[PATH]/ocaml/clambda.ml",
            "range": {
                "start": {
                    "line": 87,
                    "character": 0
                },
                "end": {
                    "line": 91,
                    "character": 37
                }
            }
        }
    },
```

At the same time "Go to type definition" works fine and finds the file under `middle_end` dir; so it seems that the problem is specific to workspace symbols query.

The dune file has `copy` rules, perhaps they confuse the LSP. I see that a similar issue was reported for 'go-to-def' in #470.

**Comment by rgrinberg** [comment]
@tatchi mind taking a look?

**Comment by tatchi** [comment]
> @tatchi mind taking a look?

Sure :)
