### ISSUE TITLE
Strings that contain typable names get wrongly typed

### ISSUE THREAD

**Issue by giltho** [ocaml/ocaml-lsp#66]
When hovering over a word in a string that is a correct name of a typable entity (variable name, function name or constructor), the pop up gives the type of the entity, even if completely unrelated.
Several examples :

![image](https://user-images.githubusercontent.com/8451179/72083663-1a23fb80-32fa-11ea-8e99-9f1d33fd924b.png)

![image](https://user-images.githubusercontent.com/8451179/72083807-50fa1180-32fa-11ea-91f3-f38a74e95428.png)

![image](https://user-images.githubusercontent.com/8451179/72083937-80108300-32fa-11ea-909c-4a929ad3f30b.png)

**Comment by giltho** [comment]
This will probably be my first PR, I'm navigating through the code.
hover is executing a command with constructor `Type_enclosing`, which is in merlin. Merlin is usually able to understand that I'm expecting string (according to what the other extensions do), so I guess this is the wrong merlin command ? Maybe it should be calling `Type_expr` in this case ?

**Comment by giltho** [comment]
Scratch that, `Type_enclosing` [should be the right request](https://github.com/ocaml-lsp/ocaml-language-server/blob/master/src/bin/server/command/getType.ts#L18). So some parameters are wrong. Is there any documentation on what the parameters mean ?
```ocaml
| Type_enclosing(* *)
    :  (string * int) option * Msource.position * int option
    -> (Location.t * [`String of string | `Index of int] * is_tail_position) list t
```
there is no documentation there :(

**Comment by rgrinberg** [comment]
In general, the commands are documented in merlin's frontend. This is the `new_commands` module. For example:

```ocaml
  command "type-enclosing"
~doc:"Returns a list of type information for all expressions at given \
position, sorted by increasing size.
That is asking for type enlosing around `2` in `string_of_int 2` will return \
the types of `2 : int` and `string_of_int 2 : string`.

If `-expression` and `-cursor` are specified, the first result will be the type
relevant to the prefix ending at the `cursor` offset.

`-index` can be used to print only one type information. This is useful to
query the types lazily: normally, Merlin would return the signature of all
enclosing modules, which can be very expensive.

The result is returned as a list of:
```javascript
{
  'start': position,
  'end': position,
  'type': string,
  // is this expression not in tail position, in tail position, \
or even a tail call?
  'tail': ('no' | 'position' | 'call')
}
```"
    ~spec: [
      arg "-position" "<position> Position to complete"
        (marg_position (fun pos (expr,cursor,_pos,index) -> (expr,cursor,pos,index)));
      optional "-expression" "<string> Expression to type"
        (Marg.param "string" (fun expr (_expr,cursor,pos,index) -> (expr,cursor,pos,index)));
      optional "-cursor" "<int> Position of the cursor inside expression"
        (Marg.param "int" (fun cursor (expr,_cursor,pos,index) ->
            match int_of_string cursor with
            | cursor -> (expr,cursor,pos,index)
            | exception _ ->
              failwith "cursor should be an integer"
          ));
      optional "-index" "<int> Only print type of <index>'th result"
        (Marg.param "int" (fun index (expr,cursor,pos,_index) ->
            match int_of_string index with
            | index -> (expr,cursor,pos,Some index)
            | exception _ ->
              failwith "index should be an integer"
          ));
    ]
```

**Comment by giltho** [comment]
Ah thank you !
I've been looking a bit more at it. On type_enclosing query, merlin returns
```ocaml
["float -> float"; "string"]
```
when hovering `log` in `let x = "log"`.

I couldn't understand why the old extension, which was using the exact same request, was giving the right answer and this one is not, but actually, I checked again, and it does the same thing. So I guess it's a merlin issue ? It shouldn't give the first result probably...

**Comment by giltho** [comment]
Let's close this

**Comment by tcoopman** [comment]
Has an issue of this been created on merlin? I can't seem to find it.

**Comment by giltho** [comment]
Hmmmm, I thought I opened one but apparently I didn't.
My bad sorry, I'll do it right away
