### ISSUE TITLE
Assertion failed on `to_jsonrpc` for `Unknown_notification`

### ISSUE THREAD

**Issue by xldenis** [ocaml/ocaml-lsp#667]
Currently `to_jsonrpc` in `Server_notification` raises an assertion failed when you attempt to serialize an `Unknown_notification`. I feel like ideally when we call `to_jsonrpc` in that case it should just return the contents of the notification directly.

**Comment by rgrinberg** [comment]
Thanks for the report. #669 addresses this.

**Comment by xldenis** [comment]
Thanks!
