### ISSUE TITLE
Unit tests are failing on Windows

### ISSUE THREAD

**Issue by tatchi** [ocaml/ocaml-lsp#684]
See: https://github.com/ocaml/ocaml-lsp/runs/6067512569?check_suite_focus=true

```diff
diff --git a/_build/default/jsonrpc-fiber/test/jsonrpc_fiber_tests.ml b/_build/default/jsonrpc-fiber/test/jsonrpc_fiber_tests.ml.corrected
index 32[26](https://github.com/ocaml/ocaml-lsp/runs/6067512569?check_suite_focus=true#step:11:26)5b1..80ccc0b 100755
--- a/_build/default/jsonrpc-fiber/test/jsonrpc_fiber_tests.ml
+++ b/_build/default/jsonrpc-fiber/test/jsonrpc_fiber_tests.ml.corrected
@@ -263,7 +263,7 @@ let%expect_test "test from jsonrpc_test.ml" =
     Uncaught error when handling notification:
     { "method": "raise", "jsonrpc": "2.0" }
     Error:
-    [ { exn = "Failure(\"special failure\")"; backtrace = "" } ]
+    [ { exn = "(Failure \"special failure\")"; backtrace = "" } ]
     <opaque>
     { "id": 10, "jsonrpc": "2.0", "result": 1 }
     { "id": "testing", "jsonrpc": "2.0", "result": 2 } |}]
```

@rgrinberg any idea what might cause that?

**Comment by rgrinberg** [comment]
I think it's just an issue with the version of ppx_expect. Which version is being selected on windows vs linux?

**Comment by tatchi** [comment]
> I think it's just an issue with the version of ppx_expect. Which version is being selected on windows vs linux?

That's indeed what's causing the issue. On Linux, version `0.15.0` is selected, while on Windows `0.14.2` is used. I tried to force version `0.15.0` but then there are some dependency conflicts on Windows: https://github.com/tatchi/ocaml-lsp/runs/6090158408?check_suite_focus=true

Forcing version `0.14.2` produces the same error as shown in my first post on all 3 platforms. So at least we've something consistent. Is it a reasonable solution?

**Comment by tatchi** [comment]
Btw, do you know why there are dependency conflicts only for Windows and not on Linux/MacOS when using `ppx_expec.0.15.0` ?

**Comment by rgrinberg** [comment]
> Forcing version 0.14.2 produces the same error as shown in my first post on all 3 platforms. So at least we've something consistent. Is it a reasonable solution?

I suppose it's better than the current situation.

**Comment by tatchi** [comment]
Seems like it's due to a different version of `sexplib0` that changed the way exception are printed: https://github.com/ocaml-ppx/ppxlib/pull/327#issuecomment-1093264726
