### ISSUE TITLE
Support building with dune 1

### ISSUE THREAD

**Issue by artempyanykh** [ocaml/ocaml-lsp#69]
Currently, build of ocaml-lsp fails with duen 2 requiring dune 1.x. Are there plan to support dune 2?

**Comment by rgrinberg** [comment]
What error do you get? I'm using 2.1 and it works fine for me.

**Comment by artempyanykh** [comment]
🤦‍♂️I got this the other way around  - **my switch** uses dune 1.11 and syntax-shims use dune 2.0. @rgrinberg sorry, for the confusion.

Anyhow, am I out of luck with dune 1.11 and need to update to dune 2 to use ocaml-lsp in my project?

```
#=== ERROR while compiling ocaml-lsp-server.~dev ==============================#
# context     2.0.5 | macos/x86_64 | ocaml-variants.4.08.1+flambda | pinned(git+https://github.com/ocaml/ocaml-lsp.git#567e960b)
# path        ~/.opam/ocaml-variants.4.08.1+flambda/.opam-switch/build/ocaml-lsp-server.~dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -j 11 --root . --ignore-promoted-rules --no-config --profile release ocaml-lsp-server.install
# exit-code   1
# env-file    ~/.opam/log/ocaml-lsp-server-28291-ebe0e0.env
# output-file ~/.opam/log/ocaml-lsp-server-28291-ebe0e0.out
### output ###
# File "vendor/ocaml-syntax-shims/dune-project", line 1, characters 11-14:
# 1 | (lang dune 2.0)
#                ^^^
# Error: Version 2.0 of dune is not supported.
# Supported versions:
# - 0.0
# - 1.0 to 1.11
```

**Comment by avsm** [comment]
Is there a reason you are stuck with dune 1.11 (i.e. a project that isn't compiling with dune 2) at the moment?  We're keen to resolve any problems with keeping up with the dune major bumps.

**Comment by artempyanykh** [comment]
Hi @avsm ! AFAIK last time we tried there were a few packages that didn't compile. That may not be the case now though. I'll see if we can bump infer's version of dune to 2.0.

**Comment by rgrinberg** [comment]
I understand the annoyance with dev tools forcing their versions of dependencies on your sandbox. This is something that we've tried to minimize in the LSP server by avoiding dependencies and vendoring things when possible. Unfortunately, it's not really feasible for dune. For now, bear with us and try to upgrade. As Anil said, upgrading should be mostly painless. In the long term, we'll hopefully solve this.

**Comment by avsm** [comment]
Thanks for checking @artempyanykh! Please do let us know on the dune issue track if there's anything blocking Infer's upgrade. We'd like to make sure you can remain uptodate :-)

**Comment by artempyanykh** [comment]
Thanks for help! I actually managed to update infer to build with dune 2 with no roadblocks. The only thing that left me scratching my head for a some time was a change in the `(modes)` stanza's default from `byte exe` to `exe` only.
