### ISSUE TITLE
Remove code snippets from dune diagnostics

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#710]
Currently, diagnostics from dune show code snippets but that's redundant as the user already sees code. 

<img width="538" alt="image" src="https://user-images.githubusercontent.com/16353531/172001105-20368b42-a40f-4595-9e1b-c84332940db0.png">

I would also vouch for removing "Error" part because the code is already underlined red to show it's an error and perhaps would move warning number and tag "[unused-value-declaration]" under the error message. It would make reading error messages easier on eyes.

**Comment by ulugbekna** [comment]
```
❯ dune build -w                                                                                                                                                              10:54:51
File "ocaml-lsp-server/src/semantic_highlighting.ml", line 139, characters 4-7:
139 | let foo = ()
          ^^^
Error (warning 32 [unused-value-declaration]): unused value foo.
Had errors, waiting for filesystem changes...
```

I can work on this, but I'm not sure where particularly the dune diagnostics messages processing should happen so that it doesn't break things. 

Btw, it would also make sense for merlin and dune diagnostics to have a single format. Currently, merlin warnings look like 

```
Error (warning 26): unused variable foo
```

But again "Error" prefix is unnecessary and `(warning xx)` could be moved to another line, e.g., 

```
Unused variable foo
(warning 26)
```

---

Unused variable warning in 

- rust 

<img width="672" alt="image" src="https://user-images.githubusercontent.com/16353531/172809254-fa2ed0c7-9edc-4104-8ff1-ebd614773351.png">

- golang extension 

<img width="371" alt="image" src="https://user-images.githubusercontent.com/16353531/172809216-10703db8-5ae5-46b1-a0de-13ed2a0c475f.png">

**Comment by rgrinberg** [comment]
A good start would be to add your error message to the test suite as in https://github.com/ocaml/dune/pull/5843 and see what dune thinks about it.

> Notably, changing diagnostic messages may break code actions that use diagnostic messages such as unused value handling (removal and prefixing underscore)

When we parse things into a structured format, we should be able to detect "unused x" warnings and errors from the code. We aren't going to need the prefix matching then.

**Comment by rgrinberg** [comment]
Please re-open if the issue persists.
