### ISSUE TITLE
Support for remote LSP client/server

### ISSUE THREAD

**Issue by artempyanykh** [ocaml/ocaml-lsp#76]
Emacs' `lsp-mode` support remote LSP servers via TRAMP. Unfortunately, `ocaml-lsp` comes with `:remote? nil` by default.

I tried adding a new configuration with `remote? t`
```
(lsp-register-client
 (make-lsp-client
  :new-connection
  (lsp-tramp-connection "ocamllsp")
  :major-modes '(caml-mode tuareg-mode)
  :remote? t
  :priority 0
  :server-id 'ocaml-lsp-server-remote))
```

And lsp-mode actually managed to start `ocamllsp` on remote machine, but kind of not completely as  the lsp server didn't advertise any capabilities to the client:
```
 `-[-] ocaml-lsp-server-remote:88874 status:starting
    |-[-] Buffers
    |  `-[+] Tenv.ml
    `-[+] Capabilities
```

So, I was wondering if this is something you already looked into? Or is it even the right repo to ask this question?

**Comment by rgrinberg** [comment]
Yeah, this is a current limitation. It shouldn't be very hard to lift, but it's a bit painful without introducing a dependency like Lwt that simplifies the construction of TCP servers.

**Comment by andreypopp** [comment]
Would it be possible to start lsp via ssh on a remote machine and still communicate via stdio?

**Comment by rgrinberg** [comment]
> Would it be possible to start lsp via ssh on a remote machine and still communicate via stdio?

Indeed. Or use the myriad other tunnelling solutions. I'm closing this as it's not a priority for us.
