### ISSUE TITLE
Feature: Create interface file

### ISSUE THREAD

**Issue by giltho** [ocaml/ocaml-lsp#79]
This is a commonly required request in the OCaml tooling world. It has been asked several time for dune in the past (https://github.com/ocaml/dune/issues/150) for example, and the conclusion has been reached that it should be done in the editor tooling.

What do you think about it ? Should it be done at the merlin level (https://github.com/ocaml/merlin/issues/538), at the ocaml-lsp level, or at the editor interface level (e.g. vscode-merlin).

In theory, I think it should be as factorised as possible, so not in the editor interface. This could be probably be done with a [`workspace/executeCommand`](https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand) request ?

This could be done in addition to [@rgrinberg's proposition](https://github.com/ocaml/merlin/issues/538#issuecomment-569076212) to propose custom completion in mli files

**Comment by taquangtrung** [comment]
Hi, I saw this issue was closed but don't know if this feature is already implemented?

I couldn't find any documentation about it in ocaml-lsp. Can anyone give me a reference point? 

Is it the `textDocument/signatureHelp

**Comment by smorimoto** [comment]
I think what you are looking for is here: https://github.com/ocaml/ocaml-lsp/tree/master/ocaml-lsp-server/src/custom_requests

**Comment by taquangtrung** [comment]
@smorimoto: Thanks a lot for the pointer! I think it's the feature [inferIntf](https://github.com/ocaml/ocaml-lsp/blob/master/ocaml-lsp-server/src/custom_requests/req_infer_intf.ml) that I'm looking into.

Currently, I tried to call it from Emacs by 

```lisp
(lsp-send-request (lsp-make-request "ocamllsp/inferIntf"))
``` 

but somehow the `ocamllsp` server always crashes after the invocation.

I'm figuring out what is wrong with my Emacs code...

**Comment by ulugbekna** [comment]
That request takes parameters, but afaiu you’re not sending the param to
the server. Hence it’s crashing

**Comment by taquangtrung** [comment]
@ulugbekna: Thanks for the suggestion. I'm still figuring out how to pass parameters to `ocamllsp/inferIntf`, but the documentation or sample code of `lsp-ocaml` is very limited

**Comment by rgrinberg** [comment]
Can you paste the error message for the crash? There should be no crashes when invalid arguments are provided.

Check out the ocaml-lsp-server/docs directory for documentation of the public requests. If you still can't figure it out, let us know and we'll update the docs.
