### ISSUE TITLE
Code actions don't seem to work properly

### ISSUE THREAD

**Issue by mattiasdrp** [ocaml/ocaml-lsp#797]
This may be due to a configuration problem from my side but I didn't touch them. Currently, I have only two actions that are proposed, destruct and annotate type and both of them are not what I expected:

![image](https://user-images.githubusercontent.com/5543639/180636769-ed5a29a1-89c7-4085-a64c-6ef848c28a92.png)

If I hit destruct I end up with

![image](https://user-images.githubusercontent.com/5543639/180636832-0175cab5-d0a8-46fa-b603-7e42a3165ea3.png)

If I hit type-annotate I end up with:

![image](https://user-images.githubusercontent.com/5543639/180636811-07502b1a-b09a-4c20-b84c-e40562da960e.png)

If the cursor is on `f`, it's even worse, the type annotation is the only code action proposed and it creates a syntax error:

![image](https://user-images.githubusercontent.com/5543639/180636899-1258ab1b-2539-4d6c-85fe-80fb4c981e14.png)

**Comment by ulugbekna** [comment]
What would you expect for the first two examples? 

The last one, yeah, should be fixed.

**Comment by mattiasdrp** [comment]
I thought code actions were "improvement advices", not "what can I do here". In the first two cases, there's no point telling me I can destruct an int or I can type a function argument inside its body. But once again, I may be completely wrong about what code actions are ;-)

**Comment by ulugbekna** [comment]
Code actions are more like "make some changes for me" to avoid writing code manually or to fix some error (at least for me)

**Comment by mattiasdrp** [comment]
It's not really completed, the third one is really an issue ;-)

**Comment by ulugbekna** [comment]
I created #801, should’ve mentioned it, sorry

**Comment by mattiasdrp** [comment]
Ah, sorry, thanks for it then :-)
