### ISSUE TITLE
Failed to poll dune registry

### ISSUE THREAD

**Issue by mattiasdrp** [ocaml/ocaml-lsp#802]
I don't know where I should report this issue but everytime I start the OCaml lsp server with emacs I have the following error:

```
failed to poll dune registry. Unix.Unix_error(Unix.ENOENT, "stat", "/home/mattias/.local/share/dune/rpc")
```

**Comment by rgrinberg** [comment]
It's expected. If you don't use dune in watch mode, you'll get an error like this. It's harmless and ocamllsp is working as intended.

**Comment by mattiasdrp** [comment]
Thanks for the answer. Is there a way to use it in watch mode ? Something that should be activated from emacs lsp mode? If it's not bothering you and you have them already, would you be able to point me to resources explaining how to do it?

**Comment by rgrinberg** [comment]
It's just a matter of running dune with the `-w` flag. For example `$ dune build @check -w`.

**Comment by mattiasdrp** [comment]
But is that call made by the ocaml-lsp-server or the client (in my case lsp-mode)?

**Comment by rgrinberg** [comment]
What do you mean by call?

**Comment by mattiasdrp** [comment]
Okay so currently there is no way for my lsp client to benefit from dune running in watch mode because this will be a process running in my terminal with no connection to my lsp client, if I understand correctly

**Comment by rgrinberg** [comment]
There is a benefit for your lsp client because the connection between dune and ocamllsp will be established for you automatically no matter what terminal you will run dune in watch mode.

**Comment by mattiasdrp** [comment]
Oh so I can start dune watch process in background when I start ocamllsp?

**Comment by rgrinberg** [comment]
Sure. You can start it in in the background, foreground, turn dune on and off, and everything should work automatically.

**Comment by mattiasdrp** [comment]
Great, thanks a lot :-)

**Comment by askvortsov1** [comment]
@rgrinberg Would you be open to adding "Maybe you are not running `dune` in watch mode?" to the error on https://github.com/ocaml/ocaml-lsp/blob/a2fe6ffa00c422610d693ef761d92c769a139b27/ocaml-lsp-server/src/dune.ml#L646? I ran into this while looking into another issue, and it isn't immediately clear that this is expected behavior.

I'd be happy to send a quick PR.

**Comment by rgrinberg** [comment]
Sure, that makes sense.
