### ISSUE TITLE
'ocamllsp: -32601: MethodNotFound' with open/create mli code action in Neovim

### ISSUE THREAD

**Issue by oemmerson** [ocaml/ocaml-lsp#839]
OCaml: 4.14
ocaml-lsp: 1.13.1
Neovim: 0.7.2 (Also tested with same effect on nightly.)
LSP client: Neovim's internal client.

I get `ocamllsp: -32601: MethodNotFound` error when using the open/create .mli code action in Neovim both with files that don't have an existing .mli and ones that do.
For .ml files that don't already have an interface file the action creates a blank .mli with the correct name but doesn't switch to it.
For .ml files that do have an interface, the action just causes the error and Neovim doesn't switch to the .mli.

**Comment by oemmerson** [comment]
Hi, Can you let me know what LSP capabilities Neovim needs to support this feature, so I can open a bug on their tracker?
Thanks

**Comment by rgrinberg** [comment]
It would be the `showDocument` window capability:

```
/**
	 * Window specific client capabilities.
	 */
	window?: {
	        ...
		/**
		 * Client capabilities for the show document request.
		 *
		 * @since 3.16.0
		 */
		showDocument?: [ShowDocumentClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showDocument);
	};
```
