### ISSUE TITLE
Error: The constructor Omd.Code_block expects 3 argument(s), but is applied here to 2 argument(s)

### ISSUE THREAD

**Issue by jawadcode** [ocaml/ocaml-lsp#842]
## The error:

```
$ make install
dune build @install && dune install
submodules/lev/lev/vendor/ev.c:2143:31: warning: ‘ev_default_loop_ptr’ initialized and declared ‘extern’
File "ocaml-lsp-server/src/doc_to_md.ml", line 8, characters 25-53:
8 | let to_code_block code = Omd.Code_block (ocaml, code)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: The constructor Omd.Code_block expects 3 argument(s),
       but is applied here to 2 argument(s)
make: *** [Makefile:31: install] Error 1
```

## How to reproduce:

```bash
git clone --recurse-submodules https://github.com/ocaml/ocaml-lsp.git
cd ocaml-lsp
make install
```

Current commit: `2757cdc11dd68a6b0260aa961395b5e8a995ff11`

**Comment by ulugbekna** [comment]
Hm, I don't know why but you have `omd` package v2.0.0~alpha2 installed, which we don't support. You should downgrade to v1.3.2. 

You can run `opam show omd` to see the version info. Run `opam install omd.1.3.2` to install v1.3.2. 

Do this help?

**Comment by jawadcode** [comment]
> Hm, I don't know why but you have `omd` package v2.0.0~alpha2 installed, which we don't support. You should downgrade to v1.3.2. 
> 
> You can run `opam show omd` to see the version info. Run `opam install omd.1.3.2` to install v1.3.2. 
> 
> Do this help? 

I was hoping building this from source wouldn't be reliant on opam since there's a versioning conflict caused by ocaml-lsp's dependency on omd 1.3.2 and another package's dependency on omd 2.0.0 when installing with opam

**Comment by jawadcode** [comment]
> Hm, I don't know why but you have `omd` package v2.0.0~alpha2 installed, which we don't support. You should downgrade to v1.3.2. 
> 
> You can run `opam show omd` to see the version info. Run `opam install omd.1.3.2` to install v1.3.2. 
> 
> Do this help? 

I ended up just installing ocaml-lsp with opam, the original issue was that there was a conflict between omd 1.3.2 and omd 2.0.0 but I chose to just downgrade.

**Comment by ulugbekna** [comment]
You should also be able to fix the issue with omd in olsp, if you need omd v2. It should be trivial. We'll upgrade when omd v2 is out of alpha
