### ISSUE TITLE
Making diagnostic ranges more precise 

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#845]
Having several-line diagnostics is very intrusive, especially during development when errors happen quite a bit. 

For a specific example where we could do better: 

![image](https://user-images.githubusercontent.com/16353531/185937116-ea61b40a-5f07-4240-a352-5c67e0d65e5f.png)

I don't see why we can't simply underline the type name rather than the whole definition to tell the user that the type isn't used.

**Comment by rgrinberg** [comment]
@octachron @gasche does it make sense to change the location to point directly to the type's name?

**Comment by Octachron** [comment]
Do you mean updating the error location?

**Comment by rgrinberg** [comment]
Yes

**Comment by gasche** [comment]
I think it makes sense, but I don't know whether it is easy to do. (Sometimes things in the type-checker are harder than it appears, and the "unused stuff" detection is a bit magical in a negative sense.) I expect that it should be allright. @ulugbekna, would you like to give it a try?

**Comment by ulugbekna** [comment]
> @ulugbekna <https://github.com/ulugbekna>, would you like to give it a
try?

Sure :-)

**Comment by rgrinberg** [comment]
Okay, I'm closing the issue here then. It's not possible to do implement this feature only on the lsp side anyway.
