### ISSUE TITLE
Increase the discoverability of ocaml-specific LSP extensions

### ISSUE THREAD

**Issue by petr-tik** [ocaml/ocaml-lsp#855]
As an ocaml beginner familiar with other languages and their LSP servers, I would like to easily discover and use the best LSP interfaces for each language. 

Coming from another language, I might not know about ocaml-specific LSP extensions and neither the readme, not `ocamllsp --help` documents them making it hard for me to find them. 

This will also help LSP client maintainers (lsp-mode, eglot, ones for vim) implement, update and advertise new user-facing features. 

### Prior art
Clangd has multiple extensions documented here
https://clangd.llvm.org/extensions
Rust-analyzer documents their extensions here
https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md

they are also easy to discover in the code
https://github.com/rust-lang/rust-analyzer/blob/master/crates/rust-analyzer/src/lsp_ext.rs

Some of those became proposals to the LSP spec. 
eg. I can see how `ocamllsp/open-related-source` and clangd `textDocument/switchSourceHeader` could share a proposal. 
https://github.com/ocaml/ocaml-lsp/blob/master/ocaml-lsp-server/test/e2e-new/code_actions.ml#L88
https://clangd.llvm.org/extensions#switch-between-sourceheader

**Comment by jfeser** [comment]
I've updated the README to mention the current extensions.
