### ISSUE TITLE
.merlin based projects still require a blank dune-project file

### ISSUE THREAD

**Issue by gdvolkov-isp** [ocaml/ocaml-lsp#859]
Thanks for adding the `--fallback-read-dot-merlin` option in #705!

It seemed to do nothing though, until I've looked at the code and realized why:

- [config calls get_external_config](https://github.com/ocaml/ocaml-lsp/blob/2c31f3585e2579aa0dcd5bdb9e8934760bdd859d/ocaml-lsp-server/src/merlin_config.ml#L391-L397) *and if that finds nothing, uses an initial blank config, i.e. doesn't get to reading .merlin*
- [get_external_config calls find_project_context](https://github.com/ocaml/ocaml-lsp/blob/6cbde1bded8afedef1b645ba4d77eba333d9cdc6/ocaml-lsp-server/vendor/merlin/src/kernel/mconfig.ml#L206-L209)
- [find_project_context looks for a parent directory with `dune-project` or `dune-workspace`](https://github.com/ocaml/ocaml-lsp/blob/2c31f3585e2579aa0dcd5bdb9e8934760bdd859d/ocaml-lsp-server/src/merlin_config.ml#L339)!

So currently it is necessary to `touch dune-project` to make a legacy `.merlin` non-dune project work. It would be nice if that wasn't the case.

**Comment by ulugbekna** [comment]
@anmonteiro hi! do you have opinion or would like to work on this since you authored #705 ?
