### ISSUE TITLE
[Emacs] Completion takes long time in lsp-mode

### ISSUE THREAD

**Issue by Ailrun** [ocaml/ocaml-lsp#88]
I use this server with [`lsp-mode`](https://github.com/emacs-lsp/lsp-mode) as a client.
When I choose a completed word in a completion list, `ocaml-lsp` spend a few seconds (or sometime, dozens of seconds) before it really completes the word.
It used to not spend such a long time, and other lsp servers like [`haskell-ide-engine`](https://github.com/haskell/haskell-ide-engine) and [`metals`](https://scalameta.org/metals/) don't.

I don't know what version I used before completion became slow, but now I use OCaml 4.09.0 with 8e03749ff16dcc65a146282749be897da2923e75 and OCaml 4.07.1 with 0fedbdaba753db7bb8f4169aa84631ef9c73f6b3

Could you please inspect this issue?

**Comment by rgrinberg** [comment]
I can observe this as well. This issue seems to be with the implementation of LSP on emacs as I can't observe the delay in vscode. I'll try to disable the resolution of completion items. Perhaps that will speed up things.

**Comment by Khady** [comment]
Could it be that the completion answer is a huge json and emacs is slow to parse it? Then it might be faster with emacs from master.

**Comment by Ailrun** [comment]
@rgrinberg @Khady Thank you for the responses!
However, if one of you guys' suggestion is the case, then it would affect other LSP servers with completion, wouldn't it?
I don't observe such lag in any other LSP servers I use, like (as I mentioned) HIE and metals.

**Comment by giltho** [comment]
Well in theory the size of jsons sent to the client could be reduced by separating `testDocument/completion` and `completionItem/resolve` requests. At first only computing the name and type of completions and filling each one later. That being said, I am very surprised to hear that emacs would handle jsons slower than vscode

**Comment by rgrinberg** [comment]
Emacs handles json much slower than vscode in fact. In emacs, all json parsing is done in pure elisp (27 should fix that).

**Comment by Ailrun** [comment]
Is it that slow so that it even makes completion to take a few seconds? Then are other LSP servers well-optimized against emacs? I don't know how it is slow, so these questions are just out of curiosity.

**Comment by let-def** [comment]
Early versions of Merlin communicated with Emacs directly using JSON. It was the bottleneck by far, in the ballpark of seconds (though I can't remember where it was between half a second and a few seconds).
We added a s-exp backend to Merlin specifically for Emacs, and latency decreased to below 10ms for similar tasks on my test machine (Merlin at that time was optimized for different workloads and cached more aggressively, the figures are not relevant for the current version but it was clear that JSON parsing in Emacs lisp was a big issue).

**Comment by Ailrun** [comment]
Resolved in #94.
