### ISSUE TITLE
Why omd < 2.0.0~alpha1 ?

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml-lsp#882]
When removing this constraint, I wasn't able to have a build or test failure?

Here is what I've tried: https://github.com/ocaml/ocaml-lsp/pull/881

**Comment by cuihtlauac** [comment]
Ok, I'm seeing the failure:

https://github.com/ocaml/ocaml-lsp/actions/runs/3279345829/jobs/5398778289

It wasn't showing up on my machine.

**Comment by ulugbekna** [comment]
This's been answered here: https://github.com/ocaml/ocaml-lsp/pull/881#issuecomment-1288867716
