### ISSUE TITLE
Locate failing with "not in environment" 

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#898]
## Problem

Go-to-def, go-to-declaration stop working after the first time going to the file of interest. 

## How to reproduce:

1. open `src/import.ml` in vscode_ocaml_platform project. 
2. trigger go-to-def on `Ocaml_version` module name line 210. This opens `.../ocaml_version.ml` 
3. switch back to file `src/import.ml` 
4. trigger again go-to-def on `Ocaml_version` → locate fails with message “not in environment: Ocaml_version” 

## Interesting observations:

- I thought whether opening `ocaml_version.ml` is causing this problem, so I put code in `ocaml_lsp_server.ml` (ocaml-lsp project) that would ignore the notification `textDocument/didOpen` if the file name is `ocaml_version.ml` . Indeed! After adding this code, I don’t observe this problem, so opening the file must be causing the problem.
    - either olsp opens a file and that triggers some problem in environments
    - or merlin is getting incorrect environment when a file is opened

- [https://github.com/ocaml/ocaml-lsp/blob/2cca06fa208318dadadcce05b60438f86f4cad63/ocaml-lsp-server/vendor/merlin/src/analysis/locate.ml#L765](https://github.com/ocaml/ocaml-lsp/blob/2cca06fa208318dadadcce05b60438f86f4cad63/ocaml-lsp-server/vendor/merlin/src/analysis/locate.ml#L765) is the first place that’s causing the error. `Env_lookup.in_namespaces nss ident env` returns `None`. The function that it invokes is `Env.find_module_by_name` that uses `Location.(!input_name)` that's equal to `import.ml` on the first run of go-to-def and `ocaml_version.ml` on the second run. Changing it on `Query_commands.dispatch` as such `Location.(input_name := (Mpipeline.final_config pipeline).Mconfig.query.filename);` before the main pattern match doesn't help.

- Invoking go-to-def on some other symbol in `import.ml` and coming back to `Ocaml_version` symbol and then doing go-to-def seems to fix it. 

----

Something similar was reported here before - https://github.com/ocamllabs/vscode-ocaml-platform/issues/970
The error message isn't exactly the same however

**Comment by ulugbekna** [comment]
Hi Ulysse, do you have any ideas why this may be happening or where I should look? @voodoos

**Comment by voodoos** [comment]
I would guess a configuration issue ?
Maybe OCaml-LSP doesn't refresh the configuration when coming back to the initial file ?
(I will try to reproduce when I find some time.)

**Comment by ulugbekna** [comment]
Fixed in #904
