### ISSUE TITLE
Unexpected `Uninterpreted extension` error on Linux systems without `/bin/bash`

### ISSUE THREAD

**Issue by LogicalOverflow** [ocaml/ocaml-lsp#903]
The vendored merlin invokes bash using the hard-coded path `/bin/bash` to run system commands: https://github.com/ocaml/ocaml-lsp/blob/2d140c86c93e2714509cc0b1cae3b38e1c1f5bd3/ocaml-lsp-server/vendor/merlin/src/ocaml/driver/pparse.ml#L49

This breaks when using ppx on a Linux system where bash is not located there (like NixOS), resulting in an `Uninterpreted extension` error being displayed in the editor. It might also break other things, but this is the problem I ran into.

An easy solution would be to use `/bin/sh` instead of `/bin/bash`, but this would break invocations with commands that rely on bash features. I don't know if that's the case anywhere.

**Comment by LogicalOverflow** [comment]
I just took a look at the commit that introduced the change (https://github.com/rgrinberg/merlin/commit/4c0d662f5eaa91bae68d6b04e4c4c2ab54e3e1c7) and I think just switching to `/bin/sh` should be fine, considering that `Sys.command` also uses `sh` to run the passed command.

**Comment by rgrinberg** [comment]
Your fix looks reasonable.
