### ISSUE TITLE
Segfault on windows

### ISSUE THREAD

**Issue by mlasson** [ocaml/ocaml-lsp#929]
# Description 

There's a "looping thread" that tries to repetitively read the file statistics (ie. Unix.stat) of the file "C:\Users\marcl\AppData\Local\dune/rpc" in order to communicate with running instances of dune watch (are there users of dune watch on windows yet ?).

When the file is absent, you'll get in the output:
```
failed to poll dune registry. Unix.Unix_error(Unix.ENOENT, "stat", "C:\\Users\\marcl\\AppData\\Local\\dune/rpc")
```
which is fine... until the OCaml heap gets corrupted which may change the error message into 
```
failed to poll dune registry. Unix.Unix_error(Unix.ENOENT, "stat", "RANDOM BINARY STRING")
```
or crash with a segfault or with "fatal: out of memory". Nasty stuff. 

In practice, ocaml-lsp is not usable on a large codebase (ocaml platform refuse to restart the server after consecutives crashes). 

I have not been able to reproduce this problem on a simple example (do not hesitate to add a smiley if you experienced the bug). 

But there is a fix: https://github.com/ocaml/ocaml/pull/11737.

The problem seems to come from a non "thread-safe" implementation of Unix.stat on windows.

Should we turn this loop off while the fix has not been integrated into ocaml ?

**Comment by nojb** [comment]
> are there users of dune watch on windows yet ?

The feature is not yet supported (natively) on Windows, but there is an open PR for it: https://github.com/ocaml/dune/pull/6087. I hope to get it into a mergeable state soon-ish.

**Comment by nojb** [comment]
> Should we turn this loop off while the fix has not been integrated into ocaml ?

Anoter possibility is to protect the call `Unix.stat` in a critical section.

**Comment by rgrinberg** [comment]
> Should we turn this loop off while the fix has not been integrated into ocaml ?

If this is done only on windows then fine.

> Anoter possibility is to protect the call Unix.stat in a critical section.

Also sounds good.

**Comment by mlasson** [comment]
> Anoter possibility is to protect the call `Unix.stat` in a critical section.

It is not completely trivial because the `Unix.stat` call in `ocaml-lsp-server/src/dune.ml` is only half of the problem. The other half in a `Unix.stat` in an unvendored dependency (merlin or dune).

**Comment by nojb** [comment]
> The other half in a `Unix.stat` in an unvendored dependency (merlin or dune).

I'm pretty sure that Merlin does not use threads. For Dune, I'm not sure if it could be affected, but @rgrinberg will probably know. On the other hand, perhaps there are other dependencies apart from Dune and Merlin, so perhaps just disabling the code altogether may indeed be safer.

**Comment by mlasson** [comment]
> I'm pretty sure that Merlin does not use threads

I don't think they need. Unix.stat must be called in an ocaml-lsp thread through some library (that may not use threads!).

**Comment by rgrinberg** [comment]
> I'm pretty sure that Merlin does not use threads. For Dune, I'm not sure if it could be affected, but @rgrinberg will probably know. On the other hand, perhaps there are other dependencies apart from Dune and Merlin, so perhaps just disabling the code altogether may indeed be safer.

Merlin does use threads, but ocamllsp runs merlin in a thread so that it doesn't block on ppx/pp processes being executed.
