### ISSUE TITLE
Stale (merlin) diagnostics reported by olsp (> 1.13.1) when used with vscode 

### ISSUE THREAD

**Issue by Kakadu** [ocaml/ocaml-lsp#941]
While using ocaml-lsp 1.14.x with VsCode ocaml-platform, I'm getting very often to the situation when VsCode highlights previous errors, which are already fixed. Usually, restarting the server helps, but not for very long. The ocaml-lsp 1.13.x doesn't have this issue, so I'm currently using the previous version.

Sorry, I'm not sure how to get meaningful log.

Did anybody else reported something similar?

**Comment by ulugbekna** [comment]
Could you show how such an error looks like?

Dune-reported errors shown in the editor by olsp may get stalled until you save the document. Could it be your case? Just saving the document should update the reported diagnostics

**Comment by Kakadu** [comment]
![Screenshot_20221201_003320](https://user-images.githubusercontent.com/438226/204912865-19c9b3a9-1dec-4637-ac45-6c14a68eb7bc.png)

**Comment by ulugbekna** [comment]
Looking at 1.14.0 [changes](https://github.com/ocaml/ocaml-lsp/blob/master/CHANGES.md#1140), I suspect #853 to be at fault. Nevertheless, I don't experience the problem myself. It would be very helpful if you could git bisect the problem @Kakadu. You should be able to just check out the repo, run git bisect as usual, and use `make install` to install the current HEAD. You may need to `git submodule update` to update the vendored merlin code, as far as I understand.

**Comment by Kakadu** [comment]
I will try to bisect

**Comment by rgrinberg** [comment]
@Kakadu any updates on this?

**Comment by Kakadu** [comment]
> 

No luck yet. I started to think, that this is so Heizenbuggy, that it appears before 1.13.x, but much much rarely

**Comment by Kakadu** [comment]
I didn't manage to bisect this yet, but got a video of reproduction. Maybe it will be better than nothing

https://www.youtube.com/watch?v=WyA4etBH98k
https://gist.github.com/Kakadu/ae73708222b70b6074c7555be646b849

**Comment by Kakadu** [comment]
TT, that after a few days I can't reproduce it again.

**Comment by rgrinberg** [comment]
Same as #1003. Should be fixed in the next point release.
