### ISSUE TITLE
Uri.to_path un-escaping incomplete 

### ISSUE THREAD

**Issue by Gbury** [ocaml/ocaml-lsp#95]
I remarked that some special characters escape sequences are not replaced in the `Uri.to_path` function, for instance:
- `%2B` which maps to `+`
- `%3D` which maps to `=`
- `%5E` which maps to `^`

There is almost certainly other character escape sequences not currently handled (I just happened upon these in my expérimentations), and it might benefit from the automatic translation of #87 ?
In any case, this is not blocking for me, so on this one I can wait for a generic solution, :)

**Comment by giltho** [comment]
(Is this still a thing given #87 has been merged ?)

**Comment by Gbury** [comment]
I'll try and check but first i'll have to adapt my code following all the changes and it might take a few days, ^^

**Comment by giltho** [comment]
Well, actually, you don't need to
```ocaml
let to_path (uri : t) =
  let path =
    match String.drop_prefix ~prefix:proto uri with
    | Some path -> path
    | None -> uri
  in
  path
  |> String.replace_all ~pattern:"\\" ~with_:"/"
  |> String.replace_all ~pattern:"%3A" ~with_:":"
  |> String.replace_all ~pattern:"%5C" ~with_:"/"
```
This is the full implementation of `to_path`
