### ISSUE TITLE
Default capabilities for text document synchronization

### ISSUE THREAD

**Issue by Gbury** [ocaml/ocaml-lsp#96]
It appears the when the client omits the synchronization capabilities (aka the `Initialize.Synchronization.t` value in a `TextDocumentClientCapabilities.t`), the default value is to assume that all capabilities are present, see https://github.com/ocaml/ocaml-lsp/blob/4cfc07db2eaaebc081c3276a8c67069d4b791e1e/lsp/src/initialize.ml#L486 

However, after reading the specification (see quote afterwards), it seems that if omitted, the default capabilities should be assumed to be (at least) the ones present strictly before version 3.x (but not necessarily more I suppose).

> Client capabilities got introduced with version 3.0 of the protocol. They therefore only describe capabilities that got introduced in 3.x or later. Capabilities that existed in the 2.x version of the protocol are still mandatory for clients. Clients cannot opt out of providing them. So even if a client omits the ClientCapabilities.textDocument.synchronization it is still required that the client provides text document synchronization (e.g. open, changed and close notifications).

It seems that the `willSave`, and `willSaveWaitUntil` capabilities were introduced in 3.0, so I'd guess that the `empty`, or default, synchronization capabilities should rather be:
```
let empty = { willSave = false; willSaveWaitUntil = false; didSave = true }
```

**Comment by rgrinberg** [comment]
Seems good to me. Could you send a PR to fix this?
