### ISSUE TITLE
OCaml 5.0 magic number not recognized

### ISSUE THREAD

**Issue by edwintorok** [ocaml/ocaml-lsp#974]
1.15.0~5.0preview1 does work for OCaml 5.0 usually, but sometimes I get some exceptions from the LSP server.
This appears to have been when editing a file in a directory that was previously compiled with 4.14 (although the exact conditions to trigger the issue are a little bit more complicated because I haven't been able to reproduce it with just that).
The issue appears to be in merlin (which is vendored) here, see stacktrace at https://github.com/ocaml/merlin/issues/1553

**Comment by edwintorok** [comment]
PR to merlin (which I assume will need to be merged into the submodule fork/branch once it is in upstream merlin): https://github.com/ocaml/merlin/pull/1554

**Comment by ulugbekna** [comment]
This should be fixed in a new release 1.15.0-5.0

You can for now opam pin branch `500` to get the fix
