### ISSUE TITLE
Revised Syntax

### ISSUE THREAD

**Issue by abhillman** [ocaml/ocaml-lsp#981]
Does `ocaml-lsp` support revised syntax (e.g. https://caml.inria.fr/pub/docs/manual-camlp4/manual007.html)? I'm pretty new to OCaml, so I'm not sure how common it is to use revised syntax or not.

**Comment by rgrinberg** [comment]
No support for the revised syntax. Any reason why you need it? The revised syntax is long since dead.

**Comment by abhillman** [comment]
I was not aware that it was dead! As I am such a newcomer to OCaml. Looks nice in a lot of ways. No need for it. Thanks @rgrinberg; closing.
